### ISSUE TITLE
Solve nightly data import timeout error

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1023]
# `Delayed::Worker.max_run_time is only 14400 seconds`

14400 seconds ==> 4 hours

**Comment by kevinrobinson** [comment]
@alexsoble https://github.com/studentinsights/studentinsights/issues/993 and https://github.com/studentinsights/studentinsights/pull/1050 seem awesome!

We might want to optimize the time the job takes to run, but right now it seems like the immediate problem is hitting that timeout, so could we 1) increase the timeout? or 2) break up the job so one job runs the STAR importers and the other one runs the Aspen importers?  Just trying to help with finding something that gets the data flowing again so it's fresh and clean for folks tomorrow!

**Comment by jhilde** [comment]
@kevinrobinson @alexsoble I'd be willing to bet #1051 will allow the rest of the imports to execute in under 4 hours. @alexsoble do you want to manually kick off the imports to see if that's the case?

**Comment by alexsoble** [comment]
@jhilde — Kicked off a new job!

@kevinrobinson — Upping the timeout limit! https://github.com/studentinsights/studentinsights/pull/1052

**Comment by jhilde** [comment]
Looks like this succeeded if not for the bug I introduced with checking on school_type = "HS" for the risk calculation. @kevinrobinson has graciously fixed in #1054.

**Comment by jhilde** [comment]
@alexsoble and @kevinrobinson: At first, my assumption was that the cause of the problem was a ton of SQL queries (~800K) to get student.id from local_id and check if the event already exists. So IMHO, reducing the queries by 1/2 would likely improve things...but I wasn't sure that's all of it.

I'm wondering if the problem is in reading the CSV file and how memory-bound we seem to be at times. From my quick reading of the code, it looks like we are reading the CSV file (22 MB this morning) into a string. We then pass that string to CSV for transformation. 

This article (https://dalibornasevic.com/posts/68-processing-large-csv-files-with-ruby) goes over some performance testing with Ruby::CSV. Take a look at the final test using an IO stream to initialize the CSV. We would need to restructure the code, namely the check for a row that should be thrown out.

But it feels like this would offer some promise. Let me know your thoughts.

**Comment by jhilde** [comment]
In many ways 22MB doesn't sound like a huge amount in memory. But it seems our steady state is to be at or above our max memory on the dyno. So I'm imagining that we are swapping a fair amount, not just for the importer but other pieces as well.

Would it be worthwhile increasing the dyno size, at least temporarily? Or spin up a separate dyno to run the imports?

**Comment by kevinrobinson** [comment]
@alexsoble Looks like we we're 2/3 from the run we kicked off this morning, and I'm figuring you retried the third one manually based on this and there being no ErrorMailer reports.

<img width="1280" alt="screen shot 2017-09-19 at 7 14 41 pm" src="https://user-images.githubusercontent.com/1056957/30619719-e70aced6-9d6e-11e7-96dc-2c9de6b3508a.png">

If you have info from that I could help debug, but I can't do much more until tomorrow night.

**Comment by kevinrobinson** [comment]
This morning it looks like the three scheduled import jobs all ran to completion (with various log messages about bad records within each job):

<img width="707" alt="screen shot 2017-09-20 at 7 40 03 am" src="https://user-images.githubusercontent.com/1056957/30642020-1f0a265c-9dd7-11e7-9c1d-55e7d8fcd032.png">

Based on the timings, there's two that didn't complete and one that took five hours.  From looking at logentries, it's both unclear how those were run (I didn't find command line jobs for them), and unclear what was run that took 5 hours.  It'd help to put this inline in the `ImportRecord` and I can look at that next week.  Aside from that, the jobs are running healthy again (20min for STAR, 89min for X2-attendance, and 115min for X2 attendance).

Also, amongst import jobs the memory errors are isolated to the attendance import job.  My vote would be to focus any optimization efforts on end-user latency (or memory usage in the main web dyno), since that directly impacts the user experience.  I'd also be in favor of buying bigger computers, since it's relatively inexpensive (we pay more for tooling than computers now), and will be far cheaper than us optimizing these things :)

**Comment by jhilde** [comment]
Good timing! Uri was doing data validation for grades this morning and said everything is accurate. (It can be difficult to validate because grades change frequently and there’s no way to know when a grade changed in Aspen’s interface.)

I did some thinking / coding for a refactor of imports last night. I’ll share today or tomorrow some of the code. 

Essentially, my drivers are performance, enhanced logging, and simplicity of implementing new imports.

For performance: 

switching CSV parsing using a string in memory to a file stream

expanding the lookup caching

For enhanced logging:

creating import_records_importer to log # of rows processed, # of rows rejected so we can have a better idea of what’s happening.

For simplicity:

As suggested collapsing the importers and rows.

Creating before and after import hooks. (i.e. setup lookup caches, delete db rows, etc.)

There’s a part of me that wants to have an eye to how will this work with several schools with potentially different file structures. For the moment, I’m turning the volume of those thoughts down. 

Appreciate your thoughts on the high level.

I agree with Kevin that performance of the site to users is the most important, just want to do this relatively quick tweak so we don’t need to worry about 5 hours of imports. ;-) 

On Sun, Sep 17, 2017 at 8:01 AM Kevin Robinson

<
mailto:Kevin Robinson <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/alexsoble https://github.com/studentinsights/studentinsights/issues/993
and
https://github.com/studentinsights/studentinsights/pull/1050
seem awesome!

We might want to optimize the time the job takes to run, but right now it seems like the immediate problem is hitting that timeout, so could we 1) increase the timeout? or 2) break up the job so one job runs the STAR importers and the other one runs the Aspen importers? Just trying to help with finding something that gets the data flowing again so it's fresh and clean for folks tomorrow!

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/studentinsights/studentinsights/issues/1023#issuecomment-330038945
, or

**Comment by alexsoble** [comment]
Hey @jhilde! 

Of the three goals you listed my sense is that logging would add the most value.

One way to beef up the logging power would be to add more information to the `ImportRecord` class which gets stored to the DB and emailed out to us if there's an error.

I'd say listen to those thoughts you're having about implementing the import process for a second district. I like Kevin's mental model of exploring ways we can "disinvest" from writing lots and lots of code for the import process. Each layer of complexity we add to the import process will be a layer we may have to rethink each time we onboard a new district.

**Comment by alexsoble** [comment]
@jhilde For performance I think we should focus on small, simple improvements that add a lot of value / fix major bugs when we find them like: 

* https://github.com/studentinsights/studentinsights/pull/1059
* https://github.com/studentinsights/studentinsights/pull/1075

**Comment by kevinrobinson** [comment]
One failure last night, but no ErrorMailer email. :(

<img width="1289" alt="screen shot 2017-09-22 at 8 36 10 am" src="https://user-images.githubusercontent.com/1056957/30744718-6776de94-9f71-11e7-80f8-b19a7f53021f.png">


So something seems broken, and hopefully the logs have more.  As a pure guess perhaps this is related to https://github.com/studentinsights/studentinsights/pull/1064.

**Comment by alexsoble** [comment]
@kevinrobinson We got an ErrorMailer email this morning!

**Comment by alexsoble** [comment]
Closing because this process isn't timing out anymore!

In fact it looks like it's gotten . . . much faster? 

![screen shot 2017-09-28 at 3 48 06 pm](https://user-images.githubusercontent.com/3209501/30989775-809b59b6-a464-11e7-9ac5-7b6702f0fd83.png)

Based on the dates looks like this is related to #1059.
