### ISSUE TITLE
Flatten importer classes so that one error doesn't stop the whole train

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1068]

**Comment by jhilde** [comment]
Mind if I take a pass at this?

On Tue, Sep 19, 2017 at 9:42 AM Alex Soble

<
mailto:Alex Soble <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/studentinsights/studentinsights/issues/1068
, or

**Comment by alexsoble** [comment]
Hey I think @kevinrobinson started some work here actually! I think it's on a branch. Just wanted to make sure we had it documented as an issue.

**Comment by kevinrobinson** [comment]
@jhilde go for it!  I fiddled with this a bit this morning, but went too far in the changes so held it back.  Branch is here if you want to look, but also feel free to ignore: https://github.com/studentinsights/studentinsights/compare/experiment/import-jobs
