### ISSUE TITLE
Add student schedule and grades to student profile (high school only)

### ISSUE THREAD

**Issue by jhilde** [studentinsights/studentinsights#1078]
This is where Uri and I came to so we can add student schedule and current grades to student profile. This is the next biggie for high school educators.

All changes will only affect students in schools with school_type of HS. This is currently just Somerville High School until we add Next Wave or other districts. **_Students profiles in for students in all other schools will remain the same._**

**Collapse Reading and Math to one panel**
The new panel will have two graphs: MCAS Scores with 2 plotlines (ELA & Math), MCAS SGP (ELA & Math) _[Rationale is to keep the scale the same]._

There will be text indicating most recent STAR scores _[Rationale is that STAR tests are only used in the elementary schools so we don't need trends in the summary, just the most recent (like 8th grade scores).]_

When a user clicks on the Reading / Math panel, the details from the panel will be combined.

**Create a schedule panel**
The summary panel will include all courses in the current semester (so current term + full year courses). Essentially <section_number (first n characters)> <grade_numeric>. 

If the educator has permission to view a section, that section will be a link to section view. Otherwise, they will just see text. [To be explicit, educators who have permission to view a student's profile will be able to see the student's grade in all current year sections, regardless of whether or not they have permission to view the sections.]

Clicking on the schedule panel will change the details pane to a new schedule pane. The pane will include all courses for the current school year. 

So: <section_number> <grade_numeric> <educators> <schedule> (maybe also room)

**Outstanding Questions**
- Still need to understand how the grades file is generated. (It's a "proprietary feed" from the vendor written in Java. My imagination is that it is pulling assignment grades and grading rubrics from Aspen then calculating a current average. It's unclear to me what happens when grades (done on a quarter system) are posted. From Aspen's interface, it looks like the average is eliminated and a posted grade is created. 

**Things to note**

- To accomplish the summary only showing current semester, we'll need to know the semester start dates. Unfortunately it doesn't seem this information exists in Aspen. So initially, the dates for this year will be hard coded into the database. In the future, we made add an interface to change them in the admin dashboard. 

- Some of this will be Somerville specific. Terms in Aspen are configurable, some districts have trimesters, quarters, some use different identifiers for different terms.

**Comment by jhilde** [comment]
A bit of original history in #1038.

**Comment by kevinrobinson** [comment]
@jhilde Sweet!  It seems like the big thing here is the product and UI changes.

This will be a good place for us to try balancing the complexity of customizing HS/other schools and simplicity, both from a product sense and from a UI engineering sense.  If it's helpful to mock stuff up and bounce things around there let me know.  Looking ahead, I think there's a good chance that this will come up continually over the next few months if we choose to add more import data, and so it might be worth picking a scope for that and doing the design work to tackle a few at once so that we have a better chance at picking useful customization boundaries.  This proposal here seems like it's a middle ground, and while this also depends on timing, I wanted to share the thought as you decide what's best.

re: authorization... I captured an idea [here](https://github.com/studentinsights/studentinsights/issues/1080), which we can figure out separately from this particular PR (if we want to at all).

re: "we don't need trends in the summary" and showing single-data points for high school grades... both of these seem in contrast what I thought we'd want educationally, which is to avoid representations of students that collapse down into single data points.  For HS, collapsing STAR Is less concerning, but particularly if we're showing educators high-stakes data in Student Insights when we don't understand how it's computed, that seems a little concerning.  My intention here is just to add a perspective as you and Uri decide together how to tackle this feature and work.

**Comment by jhilde** [comment]
Good conversation from @kevinrobinson here and along with @snoopyuri and @alexsoble in our meeting.

It sounds like there's consensus on starting with the section data only in the details of the Overview panel. (And I'll likely add some indication that section data can be found in the details). 

I'll add the sections there for high school students. I think doing anything smarter with the school year terms will enter complexity that's hard-coded for Somerville. So they will likely be grouped by the term_local_id (1, 2, 9 for Somerville High School).

Seems like at some point we need to figure out where reference data belongs (database, environment config file, etc). For each district, we'll need to model referential data of all sorts. For instance in Aspen, there's reference data to define terms, map them to the year, and map them to grade terms. We'll likely need to replicate such reference data in Student Insights for each district. [I'll leave that for another day though 😃.

**Comment by jhilde** [comment]
Here's what it looks like now. Would love some feedback @snoopyuri @kevinrobinson 

Added a little teaser to the Overview summary. Given the layout, it didn't seem to make sense to limit the table to less than full screen so it might look a bit stretched.

Columns look good? Order?

<img width="1207" alt="screen shot 2017-09-25 at 10 25 00 am" src="https://user-images.githubusercontent.com/2595259/30813638-f7b42b30-a1db-11e7-82dd-efdb33cfa235.png">

**Comment by snoopyuri** [comment]
This actually looks really good.  Really clean.  Just showed it to someone.

The only thing you might do is just make it read: Sections (3) than write it all out which might be too much test.

**Comment by jhilde** [comment]
Thanks for the quick feedback @snoopyuri! Changed to still have the sections title and 1 bullet beneath that indicates # of sections (e.g. 3 sections).

Will work on getting into production.

**Comment by kevinrobinson** [comment]
@jhilde awesome! :)

**Comment by jhilde** [comment]
Deployed to production with #1107

**Comment by snoopyuri** [comment]
Just tried it.  Looks great.  Am having some SHS people try it now!
