### ISSUE TITLE
Filter by House and Counselor in Overview (SHS)

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1086]
SHS is broken down into 4 houses (Broadway, Elm, Highland, etc.) - Housemasters will need to be able to filter out the kids in their overview tab and then be able to further filter by absences, discipline, or last SST.  Same for the counselors in each house.  Could possibly fit under tardies.

**Comment by jhilde** [comment]
Have we decided how to approach this, since house is definitely Somerville specific and counselor is drawn from a custom field in Aspen. Thoughts @alexsoble @kevinrobinson @snoopyuri

**Comment by jhilde** [comment]
If we decide yes, I was trying to centralize the student data import add-ons a bit in #1012.

**Comment by kevinrobinson** [comment]
@jhilde Am I following, is the idea here is that there are two new user personas: house masters, and counselors, and we'd be re-purposing the school overview page for them but with different sets of students?

It sounds like both bits of data are stored in custom ways in Aspen, so one option could be to make a separate import that is totally isolated, put all that data in its own table/tables (with keys into the educators or students tables as needed), and then make a UI that reads from those?  That seems like it captures that this is a very specific import, and isolated what relies on it.

Another question might be, how much do we want to support housemasters and counselors as first-class user personas with features built specifically for them?  If we had ideas about why this would be meaningful for students, or how it would support the workflows, meetings or decisions they're regularly making... that might help clarify too.

**Comment by snoopyuri** [comment]
I've got a little more perspective after sitting in the SST meetings at the high school this week.

Each house has its own SST meeting.  Their ideal workflow for the meeting is:

1) Pull up the overview page
2) Click on the filter for their House
3) Sort by attendance - discuss and dig into those kids with high absences/tardies
4) Sort by discipline incidents - do the same

Counselors go through the same process in their work and meetings.

So my gut is that I don't think we need to go as far as crafting the UI for them.  We can do it within the existing filtering system in the overview.  

As far as the custom field part and expansion to other schools, I think that every high school will have a counselor field.  Every high school might not have the "housemaster role" (wish we could get rid of that terminology), but they usually have a system for organizing students into smaller units (whether it's a house system, by grade, by program).

**Comment by jhilde** [comment]
Short term, this would be simple to implement. Counselor is likely something all districts would have. Houses is a little more difficult. Sub-groupings of students is something most districts would have as well. I seem to recall Healey having sub-groupings of students (maybe just the middle grades) where a group of educators is responsible for a grouping of students.

Here's my 2 cents on possible directions for a bit longer term (with expansion in mind):

1.) Generically model subgroupings of students as a separate table linking particular students to a particular subgroup. Subgroups would be defined in another table and be district specific. [At some point it would be cool to think about doing this across school boundaries, particularly as the district ramps up academic out of school time programming]. Educators could be assigned to subgroups as well. (Strikingly similar to sections).

We could reuse much of the school view to allow individuals who don't have school-wide access to have access to particular groups. Essentially I see the school view as a view into aggregate student data with sophisticated rollup, filtering, and sorting ability. 

Some districts might have a strong department model where the department head wants to look across all students enrolled in a section of a particular course, or all sections in their department.

I think this is all about enabling an educator or group of educators who have oversight over a grouping of students to ask questions like who's struggling, maybe even who needs more challenge, etc. Right now we do that for the most relevant case, building principal.

2.) I might envision a need to allow educators one off access to students. We could implement sub-groups simply by giving an educator (counselor or housemaster) access to those students and again reusing the school view as I mentioned above.

I prefer the 1st but also think the 2nd may be useful, especially in more one off situations.

**Comment by snoopyuri** [comment]
I would recommend that in the short term we take the simpler approach and hoping we can find a way to import the House and Counselor field from Aspen into Insights and then get it into the Filter View.  Not sure if that's coming in already on the SFTP nightly import, but just not picked up by Insights.

In the longer term, I think Justin's thinking in #1 above is strong and would allow for a lot more flexibility and for people to be more attached and accountable for subgroups of students.   I do think this could be a feature of our Roster 2.0 which would first need some focus group work to see what people ideally want to do with rosters (ex. add custom data points, create personalized groups, enter notes within the roster) and then mock up designs, etc.

**Comment by jhilde** [comment]
@snoopyuri 
**Here's some first pass info:**

1) I spoke with John Breslin. Turns out the house and counselor fields are just text fields in Aspen. So it will be difficult to do any linking, say to the counselor's educator information. We're stuck displaying or parsing the text field:

House is one of [Beacon, Elm, Highland, Broadway]
Counselor follows the format: <COUNSELOR_LAST>, <COUNSELOR_FIRST_INITIAL> x-<COUNSELOR_TEL_EXTENSION> (From the SPS website it looks like there are 11 counselors).

2) Here's a mocked up school overview (wow, by the way, way to go on the extensibility...so easy to add another filter):
<img width="1163" alt="screen shot 2017-10-12 at 2 48 38 pm" src="https://user-images.githubusercontent.com/2595259/31513885-b06f22ae-af5d-11e7-96b4-9e93433d5fe3.png">

**Some thoughts on where we should go:**

1) I think house is fine as is. Since there are only 4 possibilities it doesn't take up too much vertical real estate.

2) I'd propose taking the counselor field from the input and:

at the import level
- only taking the last name (i.e. the characters to the left of the comma)
- I thought about proper casing it (e.g KESSLER becomes Kessler) but that's difficult when you look at LABERGE to become LaBerge. So I don't think it's worth it.

at the display level
- perhaps only display the first n characters of the last name? We don't have much horizontal space. 
- collapse the counselors into the first 4 with a show all button like the services?

3) What are your thoughts on the need to include house or counselor in the student table below. Is that useful?

4) My assumption is that we will only display this information for high schools (or SHS), doesn't really matter at this point the difference until we bring on Full Circle or revisit for the next school district.

5) While I'm at it, should I add this information to the student profile?

**Comment by kevinrobinson** [comment]
👍 awesome!

re: importing counselor data, would the counselor's last name and first initial be unique enough to join them to the educators table?  If that would work, another UX thing we could do is then notice if someone is a counselor, and give them a link to their caseload on the home page (either link to the overview page with those filters in the query string, or create a separate URL for only those students).

Houses sound like they'd be different if Aspen doesn't know what house(s) an educator works with.

I was also wondering if we'd expect the set of students who have counselors to be related to the set of students who have the "counseling, in-house" service, and for those data points to be consistent.  Not sure what we'll find!

**Comment by jhilde** [comment]
@kevinrobinson 

I had thought about the matching them in the educators table as well. And yes, having educators log in to a hub page is a great idea. This is especially true for high school teachers since they currently see the details of a random section and most teach multiple sections.

There's a lot of potential, but I think we should keep this as simple as possible since it is not a long-term flexible solution but a quick, easy win for headmasters and counselors.

Houses are not supported in any way in Aspen. It's literally a random custom text field can be displayed, sorted, etc. I don't think Aspen has any concept of house for an educator. The only way to map headmaster to house is by another random text field on an individual student.

The concept of counselor isn't about counseling services, all SHS students are assigned a counselor. In my high school, we called them guidance counselors. So that's the concept, not a specific service, but an everyone has one concept.

Hopefully that helps. ;-)

**Comment by snoopyuri** [comment]
I agree with the last name approach to counselor and doesn’t need the casing as well as the ‘n’ characters of last name.  The real point is to allow them to filter quickly.  Having the house and counselor in the student profile overview would be helpful, but can come later if it’s too much for right now or involves too much customization.

**Comment by kevinrobinson** [comment]
Thanks! Yeah I missed that counselors were guidance counselors, gotcha.

And I agree on shipping the feature quickly (faster than I can respond,
which is great!).

I was thinking about how joining with educators wouldn't substantially
change the work, while adding the capacity to ask if an educator is a
counselor (using that join).  That could be something we could do afterward
if it seems like an improvement to you, either way.

**Comment by jhilde** [comment]
@snoopyuri Live in production now! Let me know if there's any feedback.

Checked with ie11, closing.
