### ISSUE TITLE
Adding New Note Types (Counselor, NEST), but worried about getting that area crowded

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1106]
Just left a SHS SST meeting.  People were jazzed about 9th grade and 10th grade note types and then requested ones for Counselor and NEST (team meeting for ELLs).  Worried that the area is going to get crowded now - there are already 6 options there.  So do we turn it into a dropdown like we'll eventually have to do for services?  Do we reduce the font/box size so more can fit?  Ideas?

**Comment by kevinrobinson** [comment]
@snoopyuri Here's some general questions and thoughts, some specific ideas, and then my own vote.

One way to think about that might be: What value do we get by knowing where the note came from?  I imagine there's a bit of value in understanding where notes are coming from within the human processes.  But we already capture which educator is writing the note.  Overall, I'd bias towards "asking people to enter more stuff is usually not worth it, unless it's really important."  And one way to ask this is: are we A) creating a general purpose note-taking system, where people will take notes about students in all different kinds of circumstances, or B) creating a system for people to use during particular meeting types, and that happens to include taking notes?

Here's a few specific ideas:
One, use a select box like we have for the educator name, where people can type whatever they want as well.  The upside is that way people can add their own over time if they want and we don't have to manage these as explicitly.  There is autocomplete to support them in choosing the same names and types (eg., once the first person puts in NEST, it's there for others to choose).  The downside is that we have less precise control over what people put, and they might put in things differently than we expect.

Two, limit the types of meetings to be more general: Academic support meeting, Social and behavioral support meeting, Language support meeting, Special education meeting, Parent conversation, Other.  The upside is that keeps the simple click on the button feel and we know what category people put the meeting in without having to figure out the specific name.  The downside is that we don't know exactly what context it came from reading the note.

My own read is that we're more towards B (creating a system for particular meetings, where notes happens to be part of that) and 1 (let people tell us what type of meeting it is rather than us defining them all).

**Comment by snoopyuri** [comment]
Thanks for thinking about this so deeply and helping me frame my thinking.  I can definitely see how this can get out of control and then we don’t really have reliable data about where notes came from.  I also am vary of going to a select box which adds more clicks to the UI.

I can see how in contexts like SST meetings, the team would want to see all their notes from the year (it’s why we added date of last SST to overview) and it acts as a log, and how that’s helpful.  Same for MTSS, NGE.  But once you get into some other incidental ones like parent conversation, counselor, you wouldn’t have a need to search or filter by these.

It could also be that in the long run we end up with a search feature in notes (sort of what I’d do in Evernote), where people could just type into the note: “NEST: Met to discuss….” and then it could be easily searchable.

**Comment by kevinrobinson** [comment]
No problem!  So yeah maybe we limit the number of meetings to the top five, keep them as buttons and then have "other" to catch anything else.  That keeps the focus on "systems to support particular meetings, and note-taking is part of that" rather than "general purpose note-taking system."

Adding search might help, although I imagine folks will usually just browse through all notes for a student if they're focused on students.  Or that it's more of an edge case for administrators to check up on people that way (when there might be ways to ask staff directly, or to look at notes by particular educators).  

Anyway, all good stuff to think about, and not sure there's a clearly better or worse approach in any of these options either, they all seem in the right direction to me :)

**Comment by kevinrobinson** [comment]
We've added both of these specific examples (eg, in https://github.com/studentinsights/studentinsights/pull/2233).  The main benefits are around sorting or searching by these now; we also might want to revisit this UI to allow more flexible entry types for specific purposes.  Either way, this issue per se is shipped.
