### ISSUE TITLE
The mini-charts don't have a mouse-hover info box or a click event to explain what they do.

### ISSUE THREAD

**Issue by sentientmachine** [studentinsights/studentinsights#111]
On /students/8/profile?column=ela

There is a red mini-chart there without an x or y descriptor, they do this sort of thing on etrade for plotting charts, but they have a more well defined square outline so you can get a feel for where the line is relative to the borders.  The border of these charts should be descernable so you can tell the difference between a high horizontal vs low horizontal.

Clicking on them should bring up the full description of what they are and help on how to interpret the chart.

**Comment by kevinrobinson** [comment]
@sentientmachine This is good feedback, thanks!

I think we'll need to validate this in real user testing, but if you or anyone else wants to try making some improvements here that would be great, and I'm happy to help try them out with folks in Somerville.

Some other thoughts:
- the top of the profile page should be an at-a-glance summary, so it'd be good to keep in mind simplicity while trying to clarify
- more details are always available by clicking into that section, so that may allow more a streamlined summary up top

Also, you had a great idea in-person to add a tutorial or something like that.  I think that's another great way to approach this, with either a written tutorial page or something more interactive built into the site.  Any prototypes of these would be most welcome too! :)
