### ISSUE TITLE
Flatten out DiscontinuedService

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1112]
Here's some interesting data from the app:

The oldest service object was created  Fri, 04 Mar 2016, more than 18 months ago.

There are 2157 service records. 

We currently set a `has_many :discontinued_services` relationship on Service, so a service can be Discontinued mutliple times. 

I ran a query to find out how often that has happened in the app:

```
irb(main):006:0> s = Service.all.map do |s|
irb(main):007:1* s.discontinued_services.count
irb(main):008:1> end

irb(main):010:0> s.uniq
=> [0, 1]
```
No service has more than one DiscontinuedService record associated with it. 

Makes me wonder if it would be simpler to manage discontinuing in a denormalized way, as an attribute on Service, instead of as a whole separate model.

@Jngai's PR #1105 got me thinking about this!

**Comment by Jngai** [comment]
@alexsoble I can continue to work on this next week.

**Comment by alexsoble** [comment]
Hey @Jngai! Cool. This would be a pretty significant data model change, so I want to see what input the team has — looks like my Issue description has a 👍  from @kevinrobinson. @jhilde, any comments or insights on this proposed change? 

Making sure we have accurate data on Services is central to the project's success so I think any change that makes the Services feature simpler and less exposed to bugs is a valuable one.

**Comment by kevinrobinson** [comment]
Hi pals!  Here's the original PR if that's helpful https://github.com/studentinsights/studentinsights/pull/257.  I think it's probably important to capture user actions and the full change history, but finding simpler ways to do that seems great.  👍

**Comment by alexsoble** [comment]
@kevinrobinson Great points! To capture the full change history we'd need to make new fields on the `Service` object to store the ID of the educator who discontinued the service.

**Comment by alexsoble** [comment]
@Jngai is going to look through the codebase and investigate what making this change would look like!

**Comment by kevinrobinson** [comment]
@alexsoble In the original implementation, that's happening in [DiscontinuedService#recorded_by_educator](https://github.com/studentinsights/studentinsights/blob/master/app/models/discontinued_service.rb#L3).  Logically, Service is storing the information from when the user said "create a thing", and DiscontinuedService is storing the information from when the user said "discontinue"

**Comment by Jngai** [comment]
@alexsoble Please excuse my handwriting 

![7eed2184-27b2-4624-af41-04615e5a596c](https://user-images.githubusercontent.com/1547934/31627985-2b90310e-b27d-11e7-885f-a60de29e1820.jpeg)

My usual approach is to do a audit of the table design. Basically I drew the two tables out a bit and walked it through rules that it should follow like if its in `normal` format and if it has the proper `relationship`. 

- It is atomic meaning that every column has been broken down to what it should be. 
- One to many relationship no longer applies since you see that 
> No service has more than one DiscontinuedService record associated with it.
You make a one to one table if it allows you to write faster query, avoid null values, and or restrict/make it less accessible. 
- Usually you don’t split into two tables unless its difficult to query. 
- `Recorded_at` seems identical to `created_at` unless there is a scenario where it isn't so. Please confirm. 
- @kevinrobinson  There is already a `recorded_by_educator_id` in the services table and `belongs_to :recorded_by_educator, class_name: 'Educator'` in services model too.

We should scrap the discontinued_services table since the one to many relationship no longer applies. One to one doesn't make sense. Query from main services table is enough. 

FYI I think services table has the potential to be a `junction table`.

**Comment by alexsoble** [comment]
Hey @Jngai! What you say makes sense to me. In a way, the services table is already a junction table or a join table between ServiceType, Student, and Educator — is that what you mean or do you mean something different?

**Comment by Jngai** [comment]
@alexsoble Yes that is what I mean. I only look at `services` and `discontinued_services` but noticed `service_upload_id` and `service_type_id` within `services` so I figured there are other tables linked to `services` which I haven't look into yet. Its not necessary right now. I figured I note it down.

**Comment by alexsoble** [comment]
Did some video chatting about this with @Jngai, we talked about two things:

+ Overall we've seen some bugs in the "Discontinued Services" world — like incorrect messages on the "Discontinue" button and unhandled edge states. Makes sense to simplify here since this is an area of the app that's been prone to bugs. 

+ This change will require ~5 changes: 

  1. Migration to flatten DiscontinuedService ~> Service
  2. Tests for the migration since it's a sensitive one 
  3. Rewire the TakeNotes JS
  4. Rewire the controller
  5. Remove DiscontinuedService model

**Comment by alexsoble** [comment]
@Jngai Hey Judy, we did this! Nice job! And it uncovered some bugs that we fixed in the process! 🎉

**Comment by Jngai** [comment]
@alexsoble Yes this one was a beast.
