### ISSUE TITLE
Handle discontinuing services that will start in the future 

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1135]
# GIF of issue 

![impossible-to-discontinue](https://user-images.githubusercontent.com/3209501/31232535-d0b262c8-a9af-11e7-95a7-9fa8cc3d3a5f.gif)

**Comment by kevinrobinson** [comment]
@alexsoble The original intent was to capture the historical log of who has entered what and what changes have been made.  That allows looking back to see who has edited what (as in auditing) and also to look back historically at what services students had in past years.  So it wouldn't just be storing the current state in the database, it'd be storing it such that we capture the complete history.  This might be different than other data we store in the database, since Student Insights fully owns this.

My overall mental model is: somewhere we want a log of all the things that have happened.  This could be done directly in the data model as it was initially (eg., when users create a service we make a record for that, and then when they discontinue it we make a DiscontinuedService for that).  The downside is at read time you have to merge those things together to understand the current state.  Or the data model could model the current state, and we write the set of changes somewhere else where we could recreate what happened.

It sounds like the change to add "end date" complicates this, and that you all found a bunch of edge cases.  @alexsoble @Jngai you all should figure out whatever you think makes sense, and feel free to ignore what the past intents were too as you're figure out how to improve this!  If changing it to just capture the current state is simpler, and persist a log of changes to another table keeps the history, that seems great too!

**Comment by Jngai** [comment]
Check out #1138

**Comment by Jngai** [comment]
@alexsoble @kevinrobinson I think the edge cases are very useful. I do find myself coding to adjust for each edge case. I think the bigger picture is coming soon since I have to investigate #1112 . Overall I think what we added help answer multiple ways that a user would go about using the service feature. @alexsoble I just notice that the input box says **"when did they start"** so a teacher seeing that is less likely to enter a future date however it still could be possible.

**Comment by alexsoble** [comment]
Hey @kevinrobinson! I like the "somewhere we want a log of all the things that have happened" framing, that seems correct for sure.

Here's my mental model of all the things that can happen to a service:

+ **First**, educator creates the service *or* Uri bulk uploads the service.
  + `recorded_by_educator_id` captures who created the service
  + `date_started` specifies when the service started (or was meant to start)
  + `estimated_end_date` specifies when they think it will end
+ **Later**, another educator or the same educator ends the service
  + Right now we have DiscontinuedService object, but that same data could be flattened down into just two fields: a `discontinued_by_educator_id` and a `date_discontinued`

@kevinrobinson @Jngai does that line up with your mental model?

@Jngai, I think Kevin's point about maintaining a log of everything that happens is an important one. To me that says that we shouldn't delete any Service records. We could do one of two things instead: 

1. Disallow educators from entering Services with future start dates
2. Change the column name `date_started` to `estimated_date_started` to make it clear that this is just an estimate, so that it would be valid to have a Service with a `date_discontinued` that actually comes before `estimated_date_started`

Which option makes more sense to you @Jngai @kevinrobinson? I'm leaning towards (2) but both seem like good options from my vantage point.

**Comment by Jngai** [comment]
@alexsoble I prefer the first one because it only took 15 minutes. Also for (2) I don't want to add a field and then have it cause such a cascading effect. I don't think all scenarios will have its `date_started` to be `estimated_date_started` for all scenarios either. We can try #2 if you don't like the way it looks. 

<img width="417" alt="screen shot 2017-10-05 at 4 00 13 pm" src="https://user-images.githubusercontent.com/1547934/31249821-c5f764b4-a9e6-11e7-9576-2b3b4791ef77.png">

**Comment by kevinrobinson** [comment]
@alexsoble Yeah, this all sounds great, thanks for explaining!  The clarification about Uri bulk uploading is good, I forgot that too.  These flattening options sound like good improvements to me. 👍   And @Jngai glad you are thinking of how to handle all the cases!

**Comment by Jngai** [comment]
@alexsoble The pr has been merged. Should we close this?

**Comment by alexsoble** [comment]
@Jngai Yeah closing now!
