### ISSUE TITLE
Notes editable by someone other than originator (permissions)

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1149]
I think that when we originally made notes editable, the only person who could edit the notes was the person who originally wrote it.   I heard from a few people that they can now edit other people's notes.  It's not urgent, but don't know if it's a permission issue or something that got lost in one of the updates.

**Comment by alexsoble** [comment]
Hey there @snoopyuri. I just read through the relevant code here. We don't limit it so that only the original note-writer can edit a note. But we do preserve the entire edit history so that we have the full log of who edited what. One future path would be to surface more of that information for users, so that it shows a little history or a summary like "Edited by Uri, Kevin, Judy, and Justin."

**Comment by kevinrobinson** [comment]
we did this!
