### ISSUE TITLE
High School Risk Levels

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1179]
Status: waiting for input from HS stakeholders on how to calculate risk levels.

**Comment by snoopyuri** [comment]
Had a productive meeting with high school team on Wednesday.  Here's what they are hoping to see in risk level calculations.  It is more complex than the elementary, but I think it's thoughtful and maybe a good way to start thinking when we look again at elementary.

+ 5 levels (0 to 4)
+ Rename to call them "Tiers" not "Risk Levels"
+ Looking at discipline actions from Aspen, not just the conduct description (not sure if we're pulling actions in as well)
+ Level 4: At least 4 F's OR less than 80% attendance over last 45 school days OR 7 or more discipline actions over the last 45 school days
+ Level 3: 3 F's OR less than 85% attendance over last 45 OR 5-6 discipline actions over the last 45 school days
+ Level 2: 2 F's OR less than 90% attendance over last 45 (no discipline involved in calculation)
+ Level 1: 1 F and 2 Ds OR less than 95% attendance over last 45 days (no discipline involved)
+ Level 0: Not any of the other levels

Happy to go back to them with any more clarification needed.  This looks big, but I think they're looking to reorganize how they tier and look at kids based on this which is very cool.

**Comment by jhilde** [comment]
Thanks @snoopyuri! I'll churn through it later today to do some thinking on:

a) if we have all the data (discipline actions)
b) how we might think about this in a broader way [i.e. other schools / districts]

**Comment by jhilde** [comment]
Some initial thoughts.

First, the level of effort is fairly significant here. Might be similar to the first high school implementation.

Looks like there are a few different data points they want to use in the calculation:

Current grade in classes: We will likely need Student Insights to know what term it currently is and how terms map to schedules.

Attendance over the last n days: This gets into the problem we identified in the attendance work. We could assume calendar days but that would reduce the accuracy. (Seems reasonable to me though for this purpose).

Discipline Actions: Pretty sure we’re not pulling actions. From looking at Aspen I have a general sense. Seems like educators can input a behavior incident which then enters into a workflow. From the data I looked at, seems the workflow is mostly just a step of what action, if any to take. Seems like there’s 0 or 1 action taken per behavior incident. We could likely pull that action, if any. (Same issue with number of days as attendance)

**Comment by jhilde** [comment]
This is likely the most Somerville-specific piece. The current elementary school risk level also falls into this category.

As much as I’d love to create some DSLish thing to express risk calculations, that’s a lot of work and not currently necessary.

If we are to support localized risk levels, it feels like we should consider moving risk / tier calculation outside the main codebase into a district-specific codebase strictly for engines. Though, depending on the imports required by new districts, the imports or a subset of them could live in district-specific codebases as well.

**Comment by kevinrobinson** [comment]
@snoopyuri jhilde This is great discussion!

Another perspective might be: As a value, we want to encourage locally-designed conceptions of how teachers and schools prioritize their efforts to support students.  And in particular we want to support any computation being well-understood and transparent to teachers, students and families.  This would be in contrast to algorithmic approaches that are opaque to educators, applied globally without respect to local context, and shift power away from teachers and towards folks who control the software.  There's a long tradition of those approaches encoding biases under the guise of the objectivity of mathematics.  I find these principles thought-provoking for this kind of work: https://www.fatml.org/resources/principles-for-accountable-algorithms

Anyway, one concrete suggestion would be to hold the assumption that we want a universally-applicable risk level formula and focus on responding to the feedback from folks in Somerville HS that the way students are marked now isn't in line with their educational values.  Other districts could then choose to opt-in to this feature and the educational values it encodes (which also requires us to be able to explain it clearly and transparently).  Or they could choose not to, or to design their own.  That way we don't have to solve that general problem now, but also flag it as "maybe not likely to generalize to an arbitrary school or district" like @jhilde is awesomely doing here.  Importantly, this conception at the high school might not generalize to other high school schools even within Somerville.

@snoopyuri and @alexsoble might remember more history (https://github.com/codeforamerica/somerville-teacher-tool/issues/280 was all I found looking quickly), but if I remember right this is exactly why Somerville isn't using the state's risk level formula - it didn't align with local intentions and "marked" too many students as at risk so as to make it not useful in practice.

**Comment by snoopyuri** [comment]
All this deep thinking about this is really great @alexsoble @jhilde @kevinrobinson , thinking about what educational values we're encoding and expansion to other districts.  Really looking forward to digging more into the accountable resource doc that Kevin attached.

In moving forward in this work, here's a possible progression (but with the caveat that I have no clue what I'm talking about when it comes to coding!):

+ 1st Iteration: Start with # of course failures within the given term - that's already available when you pull up a student's schedule in the overview tab.  Your tier would then be a simple calculation of whether you are failing 0, 1, 2, 3, 4 or more courses.  My thought is that most high schools would want this.  It also gives good added value in the short term because teams can already filter by discipline and attendance, but not by number of failures.
+ 2nd Iteration: Add overall attendance percentage into the mix, making it equal value to the course failures.  Seems like Eric has figured out a way to calculate this in the dashboard, so maybe we can draw on that.
+ 3rd Iteration: Do the 45 day calculation and the discipline actions.  By then, we should also be far along enough with other districts that we'll know what their high school needs are and how much customization will be requested.  At that point, a decision would have to be made as to Justin's point about going outside the codebase.

**Comment by kevinrobinson** [comment]
The current idea is that we may revisit this more deeply in October, but going to close this and consider this 🚢ed with https://github.com/studentinsights/studentinsights/pull/1801
