### ISSUE TITLE
Activate Capuano and Full Circle Schools

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1201]
I think we are now ready to bring Capuano (K/PreK) and Full Circle (alternative school) on board.  

The benefit would be that if Capuano SST started using it, we would have details about them when they went to Grade 1 in the 7 schools the following year.  With Full Circle on board, they could see all the notes on kids before they got referred there.

What kind of lift is that?

**Comment by alexsoble** [comment]
@snoopyuri Fairly straightforward! Before we do that I'd like to run a quick scan of the Capuano/Full Circle associated educators and send them to you to make sure the default-assigned permissions look right. We'll also need to see if the data import process runs smoothly for those schools or if they are different in some important way that might trigger a data import error. But to change the actual import process is just one line of code. 😄

**Comment by alexsoble** [comment]
## progress 

+ [ ] check default permissions 
+ [ ] check data import
+ [ ] turn on in prod

**Comment by jhilde** [comment]
Taking a look at how Full Circle will work since it is a high school but operates differently from Somerville High School.

Looks like courses, sections, educator / student section assignments are coming through in the feeds. (I'll send @snoopyuri an email with educators missing lasids).

Educators will be directed to the section page (like SHS educators are). They will see the grade column on both section roster and student profile but it will be blank. (I don't think Full Circle uses the same assessment paradigm). 

The one issue that I'll fix today is that house should not be shown, since they are not organized in that way. I will leave the counselor capability since each student is assigned a counselor.

**Comment by snoopyuri** [comment]
That makes sense….they don’t really use the gradebook, but they do have kids who move back and forth between the high school depending on how they’re doing so that information would work.
