### ISSUE TITLE
Import only what we need from jQuery UI

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1222]
Right now we include this in application.js in Sprockets, and include the whole bundle.  We only use autocomplete and datepicker.  In development, these leads to a lot of extra requests, and in production it increases the size of JS users have to download.  We should move these to be imported in components that need them (with `import`) and import only the bits we need.

**Comment by Jngai** [comment]
@alexsoble I can help with this. Feel free to assign me the next issue.

**Comment by alexsoble** [comment]
Hi @Jngai! During QA I found a bug to fix + test to add before we can ship #1165, so let's focus on getting that shipped first. 

After the services thread of work is all done, I think it would be great to focus your energy on heping us ship #1180 next.

This Issue seems like a great one for a first-timer to the project to tacle, it's straightforward and it's an optimization issue.

**Comment by kevinrobinson** [comment]
this was done!
