### ISSUE TITLE
Mention Feature for Notes

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1239]
This weekend, after talking to @gabivoicu and @alexsoble, I got some different ideas and run some possible mock-ups past different admin/teachers.  

From what I'm hearing:

+ Not necessary to have email notifications (in fact people emphatically said, no more emails!)
+ Mention (ala @ Github method) is much more preferred than Issue framework
+ No outside accountability needed.  It's enough for the person to log in and see that there's an icon showing "3 new mentions", then they click into that page and see all notes they've been mentioned on in chronological order, most recent first
+ In terms of how to mention someone, people were ok with either the @ idea with a name window popping up or by clicking on a person icon above the note, typing in the first few characters of the name, and then choosing the person (can the code be recycled from the Services side where people can select a person in the directory?).

I've put in an example here that people liked:

![mention](https://user-images.githubusercontent.com/31693366/32446764-ecdc0c06-c2d7-11e7-99b8-218b5f7fd2df.png)

**Comment by gabivoicu** [comment]
@snoopyuri 
- no more emails makes a lot of sense to me (it will also make this feature faster to implement)
- it appears to me that the only type of notification we would need is for when someone logs in a place where they can see the notes they have been mention in
- I can look tomorrow at the Services code and see if that is something we can reuse; since we already do it in that fashion in Services, it might make more sense to do it the same way here as well for consistency within the app. (@ mentions are good too, I imagine people are familiar with them from Facebook, but it seems that in the context of Student Insights, it might make more sense to stick with the list of people).

**Comment by gabivoicu** [comment]
I've thought about this some more and have more thoughts:

- when it comes to a user logging in and seeing the notes they were mentioned in, once click the icon and they go to that page where are the notes they are tagged in are, do we consider that the notification has been "read", and when they log in next time, if no new tags are made, they will not see an icon letting them about mentions in notes, correct? I am trying to figure when to show the notification and when not
- the code in Services can be reused, the question is do we want to do it that way? I have no strong preference for either, I was thinking though that the @ mention would be easier to use if a person is trying to tag multiple people in a note.

For next steps, I was thinking I am ready to do some mockups and start working on the Rails part of this(models and such). What are your thoughts, @alexsoble and @snoopyuri?

Also, Alex, can you please assign me this ticket when you get the chance so I can more easily find it? Thanks!

**Comment by alexsoble** [comment]
Over the past couple weeks we've had conversations about de-prioritizing new feature work right now, since we have a few areas in the codebase that need strengthening and we're working on deploying to a second school district. Based on those conversations with @snoopyuri, I'm going to go ahead and close this issue for now. We can re-open it when we're back in a place where it makes sense to tackle new feature work.
