### ISSUE TITLE
Fix bug: Handle data entry with invalid service end date

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1307]
Rollbar: https://rollbar.com/somerville-teacher-tool/somerville-teacher-tool/items/69/

Code:

```
       if service.save
>>>      if estimated_end_date.present? && estimated_end_date.to_time < Time.now
           service.update_attributes(:discontinued_at => estimated_end_date.to_time, :discontinued_by_educator_id => current_educator.id)
         end
         render json: serializer.serialize_service
       else
```

Thoughts: debug and then move this into the serializer object above.

**Comment by alexsoble** [comment]
Tried to reproduce this locally. Nothing seems broken about service recording, was able to record a few fake services locally with the datepicker UI.

Then I tried entering an invalid date, and was able to reproduce the error: 

## UI (inputs invalid service)

![invalid-service-input](https://user-images.githubusercontent.com/3209501/33627458-3382f6d6-d9c3-11e7-87e2-01e964c0a9b8.gif)

## Server logs

![screen shot 2017-12-05 at 1 49 00 pm](https://user-images.githubusercontent.com/3209501/33627461-35ad5636-d9c3-11e7-91de-dfc0ed526e4a.png)

What was unexpected for me was that even though the UI shows "error" at the end and doesn't update the list of services, when the user refreshes the service appears in the list, just without any expected end date: 

## UI (result)

![screen shot 2017-12-05 at 1 50 36 pm](https://user-images.githubusercontent.com/3209501/33627562-845a57a2-d9c3-11e7-9678-4afb214c1f75.png)

So this is my working theory for what cause this bug right now — a user (educator) entering invalid service end date.

**Comment by alexsoble** [comment]
Couple ideas here...

1. We should validate data entered into the service datetime inputs more strictly. 
2. We should push some of the code in students controller that's triggering this error down to the service model. It's ultimately the service model's job to determine is a service is valid or not, not the students controller.

**Comment by alexsoble** [comment]
## Client-side validation asymmetry (GIF)

Looks like we have client-side validation that would catch this for `date_started`, but no such validation for `estimated_end_date`.

![validation-asymmetry](https://user-images.githubusercontent.com/3209501/33628763-66da7b90-d9c7-11e7-8eb8-ae1ae680b0d4.gif)

**Comment by kevinrobinson** [comment]
From https://github.com/studentinsights/studentinsights/issues/1387, another test case (and the one that impacted a user last week) is leaving the end date blank.  In that case, the client code submits "Invalid date" as the value to the server, which leads to this Ruby error.

@Jngai and @alexsoble my browsing of https://github.com/studentinsights/studentinsights/pull/1105, https://github.com/studentinsights/studentinsights/pull/1004, https://github.com/studentinsights/studentinsights/pull/1097 and other related issues that we worked on is that teachers should be able to leave this field blank (which https://github.com/studentinsights/studentinsights/pull/1308 seems to confirm too).

I think we have a few separate but related questions here.  Here's a proposal for @alexsoble's item number 1 above.

1. Educators should be able to leave end date blank.  We should change the UI to allow this, and send up `null` instead of the string "Invalid date".  This change would fix the immediate bug that came up last week.  (part of @alexsoble's suggestion 1 above)
2. If there is an end date, we should validate on the client that it is an actual valid date and not allow saving until that's resolved.  That would fix the issue @alexsoble described up above. (another part of @alexsoble's suggestion 1 above) 

Separately, it was surprising to me to see the default end date being the current date.  This means the default that the product suggests for length of service is "a few seconds."  Looking in the production data, there are 18 services that look like this, and all are since 9/29/17 which is the day after https://github.com/studentinsights/studentinsights/pull/1105 shipped.  I think we might have talked about this at a previous team meeting but don't remember more and perhaps @alexsoble and @Jngai do.

My proposal for this is that we:

3. Make the default "estimated end date" blank.
4. Audit the 18 production instances, removing the end date unless there's other corroborating data that suggests "a few seconds" service duration could be plausible and accurate.

Separately, I noticed that strict parsing means you can't type dates like "2/20/18", which seems like not a great user experience.  My proposal for this is that we:

5. Use another strategy to parse the dates so that educators can write in natural formats and we assume American date ordering and accept `2/20/18` as validly representing Feb. 20th, 2018 without requiring them to type `02/20/2018`.

I haven't looked at @alexsoble's suggestion 2 above about factoring the server code differently. 

What do you all think?  I started making these changes but thought it good to share what I was thinking first. :)  If we can resolve 1 and 2 first that seems best, and then move down the line.

**Comment by kevinrobinson** [comment]
Proposed https://github.com/studentinsights/studentinsights/pull/1398.

**Comment by Jngai** [comment]
@kevinrobinson For #1387 I know not putting in an estimated end date triggers the same bug but I wonder if the error for #1387 was actually from a user putting in an invalid date like @alexsoble above "12/05/2017222" or was it actually from putting in no estimated end date. 

I reviewed my own pull requests #1004, #1105, #1097. The use case scenarios are in #1004 and those were what I answered. I never recalled a scenario where the estimated_end_date is blank and neither did I see any decision of having a blank estimated end date came up in my prs. 

#1308 does not confirm that "teachers should be able to leave this field blank" except shows what fields are currently optional and required. On the other hand this pr actually shows "estimated end date" to be optional. 

Instead of @alex idea 1, we should actually prevent user from making an unconscious mistake to begin with. UX is a field to itself and preventing user's unconscious mistake is a one of its concept. 
Check out https://www.nngroup.com/articles/slips/.

I think putting a placeholder like “XX/XX/XXXX” in the input box is already enough to prevent slips like wrong date date formats and blank fields. 

The issue of where the "default end date being the current date" is not about this issue currently open so its best to make a new issue for this.

**Comment by kevinrobinson** [comment]
@Jngai Thanks!  👍   I'll try to respond to your feedback, and I think we're mostly on the same page here about how to move forward.  Let's shape this discussion forward from https://github.com/studentinsights/studentinsights/pull/1398, to either ship that or review and propose changes or other steps we could take to resolve this issue this week, since this is an active open bug.

> For #1387 I know not putting in an estimated end date triggers the same bug but I wonder if the error for #1387 was actually from a user putting in an invalid date like @alexsoble above "12/05/2017222" or was it actually from putting in no estimated end date.

Yep, right now the client code sends up "Invalid date" in both cases, so there's no way to tell from the server which actually occurred.  But it doesn't really matter since it's a bug the way both cases are handled and we need to fix both cases :)

> I reviewed my own pull requests #1004, #1105, #1097. The use case scenarios are in #1004 and those were what I answered. I never recalled a scenario where the estimated_end_date is blank and neither did I see any decision of having a blank estimated end date came up in my prs.

Yes, I think I see the same things as you do.  I don't think there was a previous discussion of what "the default end date" should be from the perspective of the UI.  My understanding is we didn't notice the implications of setting the default date this way before, and that's the UX bug.

> #1308 does not confirm that "teachers should be able to leave this field blank" except shows what fields are currently optional and required. On the other hand this pr actually shows "estimated end date" to be optional.

Yeah, when I look at the screenshot, I see it suggesting that the "end date" should be optional and that teachers should be able to leave this blank.  I think this is the correct UX and what we want.

> Instead of @alex idea 1, we should actually prevent user from making an unconscious mistake to begin with. UX is a field to itself and preventing user's unconscious mistake is a one of its concept.
Check out https://www.nngroup.com/articles/slips/.

Definitely!  In the spirit of "Choose Good Defaults" I proposed in https://github.com/studentinsights/studentinsights/pull/1398 that we make the default estimated end date "blank."  @snoopyuri today suggested this should be "the end of the current school year," and I'll go update that on https://github.com/studentinsights/studentinsights/pull/1398 now as well.  @Jngai if you have suggestions for ways to improve the UX, please comment over there too!

> I think putting a placeholder like “XX/XX/XXXX” in the input box is already enough to prevent slips like wrong date date formats and blank fields.

I agree that "Helpful Constraints" like this are important, but I don't agree that what we've done here is enough.  Error reporting shows that users have made this mistake, and auditing the production data shows it's happened for 18 services (that each show a duration of "a few seconds").  If there are other helpful constraints we can add, let's suggest them over in https://github.com/studentinsights/studentinsights/pull/1398.

> The issue of where the "default end date being the current date" is not about this issue currently open so its best to make a new issue for this.

Maybe, but they're related and we should resolve the problem for users rather than shuffling around the discussion.  Let's get this fixed for users and focus on moving forward from https://github.com/studentinsights/studentinsights/pull/1398.

Thanks! 👍

**Comment by kevinrobinson** [comment]
@Jngai No problem, thanks for the help thinking through this!  I'll move forward from https://github.com/studentinsights/studentinsights/pull/1398 then.

And thanks for all your help and work on the project! 👍 😄
