### ISSUE TITLE
Design - Revise layout of columns in overview and profile page

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#153]
From @johnrobbjr and Kemal's great feedback [here](https://docs.google.com/presentation/d/1t7bXVaFCDU_1d0vxxnqnQ7lMBnXa8oRyYRyMLtwx0hU/edit#slide=id.g11c1c42e02_3_0).

Combine these two sections into one column, Replace “Demographics” with “Student Details”
<img width="411" alt="screen shot 2016-03-02 at 12 45 21 pm" src="https://cloud.githubusercontent.com/assets/1056957/13469269/a52324c2-e074-11e5-9028-110d1356d361.png">

**Comment by kevinrobinson** [comment]
@johnrobbjr I'd tag this one as the highest priority piece of feedback, since changing this in 3 months will be disruptive to users who have grown used to where things are laid out.  I'd also love to hear more of your thinking about this idea too.

We've talked about combining these directly as you suggest, but haven't mostly because of the appeal fo the organization and flow:

  1. what do students come in with (demographics, disabilities)
  2. how are they doing in the measures we care about (reading, math, behavior and attendance)
  3. what are we doing to support students

This isn't super clear now, so design ideas or mocks addressing clarifying this would be awesome.  Alternately, proposals for reorganizing or simplifying would be very welcome too.  These proposals will also have to address changing the content within these sections (ie., removing a column means also cutting the information in that section or moving it elsewhere) and the layout of the columns on the overview page as well.

This is a really important one, so any ideas here would be deeply appreciated! :)

**Comment by johnrobbjr** [comment]
Hey @kevinrobinson , I took a deeper look at the Readme and I now see the consistencies between the layout of the pages (demographics on the right, interventions on the right, etc.). So by modifying the order of those columns, the columns would have to be altered in the same way on the "school overview" page as well.

When I was making this suggestion I had screen real-estate in mind, but I can definitely see where the consistency between pages would help. If the structure of this section needs to be addressed, it will probably have to be looked at from a holistic view of the entire application, rather than just this page. I'll keep this in mind in case something similar comes up again, but I think he current design is fine for now.

**Comment by kevinrobinson** [comment]
@johnrobbjr Thanks for sharing such thoughtful feedback!

Yeah I'd love to explore ideas here that consider both screens, and would welcome any suggestions.  I'll leave the issue open in case any ideas come to mind, or you or anyone else is able to help in the near term.
