### ISSUE TITLE
Importer issues with failure modes

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#1626]
related issues:
- https://github.com/studentinsights/studentinsights/pull/1751
- https://github.com/studentinsights/studentinsights/pull/1750
- https://github.com/studentinsights/studentinsights/issues/1738

Fixed or improved!
--------------------------------
- @alexsoble your DNS and MailGun config changes look like they worked great!  I staretd getting SIGTERM ErrorMailer emails and ImportJob#failure emails (and I think you did too).
- I cleared out the Delayed::Job queue for New Bedford.  I have the raw data on the errors if we need it, but there have been a bunch of changes in how and what we log, so don't think this matters.
- Way too much logging for attendance and behavior importer (logging a line for every row read).  In the process I realized that the `index` being passed in for each row was nil, because of a bug in how we thought the CSV parsing worked.  That's fixed and it fixed the "undefined" showing up in the attendance importer logs too.
- The import tasks were logging a bunch of raw data for invalid rows, and this included things like teacher and student names (and maybe even could include things like addresses or phone numbers), so I removed logging for any invalid rows.  We're not looking at it now anyway, we can build a better way to look at this later if we need it.

Failure modes
--------------------------------
- Looking at the stuck Delayed::Job records, they don't show the number of attempts or failures accurately (although I think this is improved after some of these changes (eg, see #72).
- On memory errors, it looks like Heroku sends SIGKILL directly, so that just kills the process and no Delayed::Job cleanup runs.  That's not good and so doesn't help improve how we handle out of memory errors.  But, it helps improve how we handle config changes or dyno restarts or deploys.  Those will send at SIGTERM now.  But...
- It doesn't look like "destroyed_failed_jobs = false" worked.  Logs show this line: `Job ImportJob (id=73) REMOVED permanently because of 1 consecutive failures`.  That's the opposite of what I thought that config line would do :\  So I think we are still in a state where if there's a deploy, the job just gets interrupted and dropped.
- Basically, https://github.com/studentinsights/studentinsights/pull/1613 didn't really improve much.
- And in trying to debug this now, I can't seem to get the workers to pick up jobs in the queue.  It may be there's some "backoff on failure" config that I can't understand.  The README in their repo doesn't describe this though so I got stuck and couldn't debug further because I couldn't get any jobs to run.  Before stopping, I cleared the queue again so it was empty when I stopped.

Other big issues to look into
--------------------------------
- These jobs are failing because they're running out of memory.  Not sure why that is.
- Check to see if X2AssessmentImporter is running in each import once they're running stably again.
- istudent.csv is 0 bytes on SFTP site.  No idea why, but we're not importing any students.  Seems like it might be a problem on New Bedford's side?

Small improvements for after
--------------------------------
- On the import records page, the list of QueuedJobs isn't sorted
- In the import records UI, what do you think about just showing the job JSON?  locked_at is really important for debugging, and the lines showing errors and failures and attempts weren't accurate for the jobs in there earlier today (they might be after some of these improvements, not sure yet).
- For the `attendance_importer` the logging showing "rows of data in" pre-cleanup and post-cleanup is misleading.  Since this is using StreamingCsvTransformer, it doesn't know how many rows there are and so just prints those lines with no numeric value.

**Comment by alexsoble** [comment]
@kevinrobinson Since you're on vacation mode please ignore all these notes until next week, just adding them here so that we have a record of what's going on! 

Notes on notes: 

> ## @alexsoble your DNS and MailGun config changes look like they worked great!

Hmmm... This is strange and confusing to me because the NewBedford MailGun page is showing that the TXT records aren't set up properly yet! Their UI is serving up exclamation marks and "Not found." Will dig in and try to sort this out. 

![screen shot 2018-04-16 at 11 54 14 am](https://user-images.githubusercontent.com/3209501/38823774-f43025e6-416c-11e8-8cb6-95a2d01b31d4.png)
![screen shot 2018-04-16 at 11 54 12 am](https://user-images.githubusercontent.com/3209501/38823776-f55c5ff2-416c-11e8-9b12-8a7a80337494.png)

> ## I cleared out the Delayed::Job queue for New Bedford. 

Checking the New Bedford import records page, I see the queue is filling up again. So whatever is causing the jobs to get stuck in the queue is still live.

![screen shot 2018-04-16 at 11 55 03 am](https://user-images.githubusercontent.com/3209501/38823913-4705e0b2-416d-11e8-9114-b5b3ec123d02.png)

> ## Way too much logging for attendance and behavior importer (logging a line for every row read)... removed logging for any invalid rows. 

Good changes! 👍 

> ## These jobs are failing because they're running out of memory. Not sure why that is.

One thing that I'm noticing when I compare New Bedford and Somerville in the Heroku UI:

### Somerville
![screen shot 2018-04-16 at 12 00 04 pm](https://user-images.githubusercontent.com/3209501/38824074-ba306ba2-416d-11e8-823c-83fa0b28a87b.png)

### New Bedford
![screen shot 2018-04-16 at 11 59 47 am](https://user-images.githubusercontent.com/3209501/38824075-ba43c580-416d-11e8-89c7-3b96f8dd9443.png)

New Bedford doesn't seem to have any workers running. Maybe that's why jobs are not leaving the queue. I'll add a New Bedford worker now.

**Comment by alexsoble** [comment]
Cleared out the New Bedford queue, added a worker for New Bedford:

![screen shot 2018-04-16 at 12 02 46 pm](https://user-images.githubusercontent.com/3209501/38824236-3a258086-416e-11e8-9f85-a31a44cfcb01.png)

**Comment by alexsoble** [comment]
Digging in more to why the jobs are running out of memory: 

One difference I noticed between Somerville and New Bedford was that Somerville had the `--only-recent-attendance` flag turned on. This reduces the number of database queries triggered by the attendance importer and the memory allocated.

Since we've already ran the New Bedford importers to import historical attendance, I went ahead and added the `--only-recent-attendance` flag. So the job now looks like: 

```
thor import:start --only-recent-attendance --school '123' '115'
```

Will check back tomorrow to see if the memory allocation looks different in the Heroku Metrics panel.

I also checked the SFTP site to get a sense for how big these files are. 

Here's what I see:

```
newbedford  2899766 Apr 17 01:10 istudent.csv
newbedford   155879 Apr 17 00:50 istaff.csv
newbedford  3872508 Apr 17 00:30 iconduct.csv
newbedford 62826483 Apr 17 00:20 iattendance.csv
newbedford 58864898 Apr 17 00:10 iassessments.csv
```

The assessments file is almost as large as the attendance file, and an order of magnitude bigger than the rest. So if skipping non-recent attendance records creates a significant improvement in memory use, we may want to think about skipping non-recent assessment records next.

**Comment by alexsoble** [comment]
On the Mailgun config issue, created a ticket here: https://app.mailgun.com/app/support/637829

**Comment by alexsoble** [comment]
Okay, a couple of updates on this:

## 1. New Bedford memory usage improved ...

Check it out: after I changed the import task to use `--only-recent-attendance`, the memory usage on the worker dyno went way down compared to previous nights:

![screen shot 2018-04-18 at 3 44 44 pm](https://user-images.githubusercontent.com/3209501/38957458-4e379dee-4320-11e8-91ee-ffd4644c94aa.png)

## 2. But the New Bedford import job was still SIGTERM'ed last night — by a midnight deploy! 

OK, so the memory situation is much better, but when I log into the Import Records page, I see that: (a) the job still isn't reaching X2AssessmentImporter and (b) it's being SIGTERM'ed. I go and read the Heroku page about SIGTERM and read that it's usually Heroku telling a dyno to restart: https://devcenter.heroku.com/articles/dynos#graceful-shutdown-with-sigterm.

And indeed, when I check the Heroku metrics page, I see the dyno is being sent a restart command, by me, because of a deploy. And that's real — I **really did** deploy some code pretty late last night.

![screen shot 2018-04-18 at 3 52 15 pm](https://user-images.githubusercontent.com/3209501/38957670-cd67c4f4-4320-11e8-88ca-21acc00deacd.png)
 
So one takeaway here is: "When a developer deploys something late at night, it can trigger a real error and stop the import process. We should handle shutdown more gracefully." 

The Heroku docs talk about this in "Graceful shutdown with SIGTERM": 

> When the dyno manager restarts a dyno, the dyno manager will request that your processes shut down gracefully by sending them a SIGTERM signal. This signal is sent to all processes in the dyno, not just the process type... The application processes have 30 seconds to shut down cleanly (ideally, they will do so more quickly than that). During this time they should stop accepting new requests or jobs and attempt to finish their current requests, or put jobs back on the queue for other worker processes to handle. If any processes remain after that time period, the dyno manager will terminate them forcefully with SIGKILL.

## 3. All the SIGTERM Rollbar emails are coming from the Somerville app . . . and the culprit appears to be Heroku nightly restarts!

When I look at your original post up top, my assumption is that you were assuming all the SIGTERM emails were from the New Bedford app. (Hence the mention of DNS/Mailgun updates working). 

But those emails weren't from New Bedford's app, they were from Somerville — if you check the Rollbar emails about SIGTERM, you'll see`body.message.extra.district_key | somerville`. I went into the Heroku console for Somerville to see what's going on.

One thing I saw was that when the jobs end abruptly, there's a "Daily Restart" going on at the same time:

![screen shot 2018-04-18 at 4 06 41 pm](https://user-images.githubusercontent.com/3209501/38958324-8f184b90-4322-11e8-9a06-cf90b86d0947.png)

This is basically the same thing as the deploy-triggered-restart, but done by Heroku, daily. I'm not sure why we haven't experienced this as a problem before. Maybe it has to do with the interaction of how long our job takes to run, when we time our job to start, and when Heroku times their daily restarts. 

## Summary! 

We should implement the cleanup-on-SIGTERM routine Heroku describes: handle SIGTERM being sent to a running job, cleanup before the process shuts down entirely and write a short note to the logs about it. Once that's in place we should queue a new job to make sure the import process finishes. A first pass at this could just start the whole import over again, but an ideal solution would know where the old job left off and pick up from here. 

## Postscript: Mailgun for New Bedford

I'm still working on getting Mailgun, Namecheap, and Heroku to play nicely together. Luckily some web searching reveals I'm not the only one to have a hard time getting these particular tools to work together: 

* [Setup MailGun on NameCheap: SPF, DKIM, CNAME and MX](https://medium.com/@ustcboulder/setup-mailgun-on-namecheap-spf-dkim-cname-and-mx-684b5c1fb492)
* [MailGun and NameCheap: SPF and DKIM Validation](https://julienliabeuf.com/mailgun-namecheap-spf-dkim-validation/)

Based on what I learned I tried some different DNS config. Unfortunately Namecheap says it can take 48 hours for the new DNS to propagate, so it's a bit slow to debug this one. 😞

**Comment by alexsoble** [comment]
Okay, so what happened in production after #1638 shipped?

## Somerville 

The nightly job ran normally, didn't receive any deploys or restarts, and succeeded. 

Before I left work yesterday I kicked off a manual import job and then forced a `heroku restart`. 

As expected, here's what the job had to say when the dyno restarted:

![screen shot 2018-04-20 at 12 05 37 pm](https://user-images.githubusercontent.com/3209501/39064193-3831a93a-4493-11e8-9cd3-07d3ba639d45.png)

The re-queued job finished successfully. So this looks like a success for the rescue-SignalException-and-re-queue strategy of #1638!

![screen shot 2018-04-20 at 11 31 43 am](https://user-images.githubusercontent.com/3209501/39064156-0a353d62-4493-11e8-9c06-bb2c5c111dcb.png)

**Comment by kevinrobinson** [comment]
Some `Net::SSH::ConnectionTimeout` for NB came in over night, and looking at the logs quickly shows the import task running more frequently than we'd expect.  It's succeeding, but we still need to look at this.

**Comment by kevinrobinson** [comment]
Cleared the NB queue manually.

**Comment by kevinrobinson** [comment]
Cleared the queue manually.

**Comment by kevinrobinson** [comment]
Here's an update from https://github.com/studentinsights/studentinsights/pull/1861#issuecomment-401558466.

I ran several iterations on this for both sites yesterday and over the night.

```
#1629/dj615: thor import:start --background --only-recent-attendance (mistake with --skip-old-record typo)
    36 minutes (log)
  #1630/dj616: thor import:start --background --source=attendance
    93 minutes (log)
  #1631/dj620: thor import:start --background --source=assessments
    12 minutes (log)
  #1632/dj621: thor import:start --background --skip-old-records --only-recent-attendance
    38 minutes (log)
  #1633/dj622: thor import:start --background
    (aborted, dyno restart)
  #1634/dj623: thor import:start --background
    101 minutes (log)
  #1635/dj624: thor import:start --background --skip-old-records --only-recent-attendance
    33 minutes (log)
  #1636/dj625: normal daily run
    60 minutes (log)
```

new bedford
```
new bedford
  #1536/dj:190: thor import:start --school '123' '115' --background --skip-old-records --only-recent-attendance
    16 minutes (log)
  #1537/dj:191: thor import:start --school '123' '115' --background --source=attendance
    21 minutes (log)
  #1538/dj:192: thor import:start --school '123' '115' --background --source=assessments
    18 minutes (log)
  #1539/dj:193: thor import:start --school '123' '115' --background --skip-old-records --only-recent-attendance
    15 minutes (log)
  #1540/dj:194: thor import:start --school '123' '115' --background
    40 minutes (log)
  #1541/dj:195 normal daily run
    27 minutes (log)
```

So these all are healthy, and in particular this addressed the New Bedford memory pressure.  Somerville hit the soft limit for memory, so that would be the next improvement but it's not critical.  The other change I made was to add `--skip-old-records` to each job.  The intention is that we'd use that flag to control this for other tasks as we need, and that we'd migrate toward a consistent time period (ideally something longer than 90 days, since we need to be able to run backfills for work like https://github.com/studentinsights/studentinsights/issues/1657.

I verified that this didn't change any data (other than intended and called out in the PR), and spot checking this across several schools this looks good.  The only noticeable change is that the "None" value for ELA and Math MCAS at the HS went up, which makes sense that correctly changed some `scale_scores` that were coerced to 0 back to nil.

To move forward, I think there are three strands of related work:
1. Improving how failure modes are handled, so we don't get multiple jobs being continually retried. 
 https://github.com/studentinsights/studentinsights/pull/1862 could be a first step towards investigating and understanding what's happening, but let's let things run for a week to see what happens first.  We can discuss that more over in https://github.com/studentinsights/studentinsights/pull/1862.
2. Verify that running a backfill imported new fields for absence data for https://github.com/studentinsights/studentinsights/issues/1657 as expected, which is now unblocked and we can continue that work over there.
3. Digging into this surfaced several data quality, validation and UI issues related to the details of these different data sets.  The most important bit here is related to DIBELS data, which is called out separately in the work board.  Others are added into the backlog, and I have notes on specific test cases.

With that, going to close this issue as it has sprawled a bit, and we can re-open new ones as needed. cc @alexsoble
