### ISSUE TITLE
Remove v1 profile page and related code

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#211]
This is part of the cleanup for https://github.com/studentinsights/studentinsights/issues/5.

We should wait a week or two until after v2 is fully rolled out and stable.  Especially with adding new bits to the v2 profile page like DIBELS and ACCESS, it's useful to have the v1 page still around for quick validation.

There's also some CSV export logic and really good authorization tests that are written for the v1 profile page, so should move those over to the new profile page too.

Ultimately, this means we remove the redirect that's there now, and the `profile` action becomes the `show` action.

**Comment by alexsoble** [comment]
@kevinrobinson PR #281 covers the controller and view part of this issue.

It looks like there's also a data model / data migration aspect here too.

The `StudentNote` and `ProgressNote` models are used in V1 but not V2. We should delete those models (and their corresponding specs, helpers, generators, etc.) as part of this work.

There are 0 StudentNotes and 49 ProgressNotes in the production database. These were added by Jill at MTSS / SST meetings. In order to not lose this data, we'll need a migration that turns `ProgressNote` data into `EventNote` data.

**Comment by kevinrobinson** [comment]
Awesome!

Yeah and to clarify I think those models are used in v2, read and then
rendered as 'older note' or something like (although maybe not).

I had been thinking we'd just keep the old models around but I think doing
a full migration sounds like a better way to simplify. :thumbsup:

**Comment by alexsoble** [comment]
Oh yeah, you are correct! I see the "Old progress note" / "Old intervention" bit now, didn't notice before. 

In that case I think a full migration is a "nice to do" refactor but not critical. The `StudentNote` and `ProgressNote` models are still being exercised by Profile V2 so they are not just cruft, unlike the view / controller code.

**Comment by alexsoble** [comment]
Almost done here. The only code left in `app/assets/javascripts/student` is the `profile_charts` directory. Some of the V1 profile chart code is being used by V2, some is not.

So remaining steps are:

1. [ ] Figure out which `profile_charts` code is unused, delete that.
2. [ ] Move `profile_charts` code in use over to the V2 folder.
3. [ ] Get rid of the "V2" part of files, components, and folders that have it in their name. Would be a little confusing for a new contributor to see V2 everywhere when there's no more V1.
