### ISSUE TITLE
Distribute demo data attendance events evenly across school years

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#227]
Right now absences & tardies only occur with in the last 100 days:

    attendance_event.occurred_at = Time.new - (rand * 100).to_i.days

This makes stuff a little difficult to test in the UI. We should evenly distribute them over all school years.

**Comment by erose** [comment]
@kevinrobinson @alexsoble Is it easy to get the real distribution on absences/tardies? Is the current:

![screen shot 2016-04-12 at 4 43 32 pm](https://cloud.githubusercontent.com/assets/1514487/14474994/be715be6-00cd-11e6-80ae-2c14e72384ce.png)

realistic? (Thought I might fix that if I'm fixing attendance events anyway).

**Comment by kevinrobinson** [comment]
@erose Here are the real distributions as of today.  Keep in mind this is quite dependent on the time of the year since it's cumulative from the beginning of the year:

<img width="202" alt="screen shot 2016-05-01 at 10 10 51 pm" src="https://cloud.githubusercontent.com/assets/1056957/14946001/9698735e-0fe9-11e6-855c-99281ac4111e.png">

Also, I'm all for improving this but fully modeling this can be quite complex, so my suggestion would be to focus these improvements on places where it significantly interferes.

**Comment by erose** [comment]
Ah, I didn't realize these were cumulative from the beginning of the year. Okay, that does seem complicated to model. New PR generates them both according to the Absences distribution you gave but makes no attempt to model the change-over-the-school-year.

**Comment by jemagee** [comment]
Assuming that each school year has an ID can’t you just create a belongs to / has many between the school year and the absence?

**Comment by kevinrobinson** [comment]
@erose 👍

**Comment by kevinrobinson** [comment]
@jemagee hi!  I'm not sure I follow what you mean, but the question here is more about what the distributions should be than the relational modeling.
