### ISSUE TITLE
Profile page - Add ability to edit and delete notes

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#228]
Split out as an enhancement to https://github.com/studentinsights/studentinsights/issues/5.

Design should reflect that these are not the primary user interactions, and should require some kind of user confirmation to delete anything.  On the server-side, we could use an append-only log of delete and update actions (in contrast to updating the note records in-place), and merge them at read time since the volume of these changes is expected to be so low.  This is probably most beneficial for deleting, since it keep the audit trail.  As a general user experience and data provenance goal, using an audit trail with recovery can minimize the "confirmation checks" we need to require of users, since users can recover easily and quickly.

For now, we can restrict delete and edit capabilities to admin users, but as part of productionizing this we should test that with school partners.

**Comment by kevinrobinson** [comment]
@kbweaver Thanks for chatting this out in person, and for the great questions!

To capture what we talked about:
- The main scenario for editing is that a user records a note in an SST meeting, and then notices a typo mistake and wants to fix it.  Or they are reviewing a student profile and then notice a typo someone else made and they want to fix it.
- Users in schools (principals in particular) care about maintaining the integrity of the data, and guarding against any mistakes that someone might make that could lead to losing data.  One approach to handling this is to create authorization rules, that restrict which users are able to edit and delete data.  Another approach is to record more history about each change, so we (or end users) can recover if something gets deleted that shouldn't be deleted.  I think for this project we should default towards recording everything and keeping access rules open for everyone in the school.
- For approaches to recording the full history of changes, I'd suggest bias towards a simpler solution over one that's more efficient or generalizable to other cases.  The specifics of what this looks like in the database are a little different for the edit and delete cases, and treating them separately is cool.

To tackle this, you could start with what the database tables and columns would look like to support this, or what the user experience would look like, whatever you prefer.  If it's helpful to write up quick bullet points of what your plan is, I'm happy to review that too.

Thanks for your help! :smile:

**Comment by kbweaver** [comment]
Thanks @kevinrobinson !

We considered a few options for tracking edits.
- Bring in a third-party library like [Paper Trail](https://github.com/airblade/paper_trail) or [Audited](https://github.com/collectiveidea/audited). This would be very generalized and powerful at the cost of maintaining another dependency. @kevinrobinson and @alexsoble didn't anticipate a need for this type of auditing beyond event notes and services, so the business case doesn't seem compelling enough to justify the cost.
- Maintain a separate `event_note_revisions` table that points back to `event_notes`. We could keep the most recent revision in `event_notes` and only stash old versions in `event_note_revisions` when edits are made. Could be done without a data migration.
- Keep all revisions in the `event_notes` table, identified by a foreign key back to the original note (something like `event_notes.parent_event_note_id`). To optimize for reading, we could identify the most recent version with another indexed boolean column. This would likely require a data migration.

I'm leaning towards the second option since it seems the most lightweight and backwards-compatible with existing read and insert operations, and only requires some additional overhead on edit.

**Comment by kevinrobinson** [comment]
@kbweaver This is great summary of the options and tradeoffs involved!  I think going forward with either 2 or 3 sounds great.  One other benefit of 3 is that there is only one source of truth (while 2 has to double-write).

If 2 seems like the better option to you since it better supports making incremental changes then I'd say go for it!  Let me know if there's anything else I can do to help.

**Comment by kevinrobinson** [comment]
And thanks again for your help on this!  👍   This is a great example of how to communicate about the different tradeoffs in various solutions, and might be good to add a link on the readme showing the example when this is shipped.

**Comment by alexsoble** [comment]
Attended today's Student Support Team meeting at the Healey school to observe how they used Student Insights. This issue came up as the staff member taking notes made an error and wanted to delete or correct the previous notes.

The staff I spoke with (two principals and the note-taker) said that they would be alright with functionality which only let them delete a note and write a new note in its place, instead of truly revising it. In terms of authorization, one principal said that she would want the ability to delete notes created by staff in case the notes contained language that contained bias or inaccurate information about a student. This would be in addition to staff members being able to delete notes they added themselves.

**Comment by kbweaver** [comment]
Spoke with @kevinrobinson , and we're okay making the simplifying assumption that student-level authorization will be good enough for event note-level authorization (i.e., assume that if an educator has permission to view a student, they have permission to modify notes about that student). If this assumption changes in the future it shouldn't be too difficult to add a second layer of authorization.

**Comment by kbweaver** [comment]
Before closing this, we should also address some concerns around HTML sanitization that @kevinrobinson brought up. Perhaps it would make more sense to take the resizing [(textarea approach)](http://alistapart.com/article/expanding-text-areas-made-elegant).

**Comment by alexsoble** [comment]
Closing this because notes are now editable. Building functionality for deleting notes is another conversation but I haven't heard it as a high-priority ask. If we want to talk HTML sanitization (good topic IHMO) we should make a new issue.
