### ISSUE TITLE
Fix bug with handling unparseable dates in PDF export

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#2685]
The error is: `TypeError: Unable to get property 'format' of undefined or null reference`, coming from the `ProfilePdfDialog.js` file.

This looks like most code in that component expects that `this.state.filterFromDate` will always be a valid Moment object, but the event handlers like `onFilterFromDateChanged` and others can set it to null if the text value isn't parseable as a valid date.

**Comment by edavidsonsawyer** [comment]
@kevinrobinson it looks like this would be easy enough to fix by falling back to the existing date if the `filterFromDate` or `filterToDate` were null. However playing with the component it seems like the real problem might be that trying to change the date (eg. hitting delete) doesn't actually allow you to input a manual date and instead changes the date in unexpected ways, eventually leading to this error. The options I see are

1. Ensure keyboard import doesn't change the datepicker range, and rely on the modal calendars to set the dates,

2. Fix the input and make the date ranges editable while preventing invalid input

Option 2 is consistent with the service recorder so that seems like the way to go unless there's a reason I'm missing to stop users from manually setting pdf dates. Does that sound right to you?

**Comment by kevinrobinson** [comment]
@edavidsonsawyer Cool, awesome investigation! 👍 

I agree that it's a UX issue primarily if folks can't just type a date in the text box.  I also agree that option 2 sounds like the right direction - users need to be able to:
- see default date sets when the open the dialog
- be able to use the datepicker to pick different dates
- be able to type dates in the textbox
- either get feedback on invalid dates or be prevented from clicking "Generate" when invalid (rare occurrence)

Given that, the code or internals for that component could change however they need to to meet those goals.

**Comment by edavidsonsawyer** [comment]
@kevinrobinson great! I've got a branch that solves those problems so I'll add some tests and poke around with it to make sure it's working as expected and submit a PR
