### ISSUE TITLE
Update services dialog to allow free-text names for service providers

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#307]
This supports a common SST meeting use case of specific staff that work closely with the school and students but are not district employees (eg., outside counseling providers), or for cases of tutoring programs where the individual providing services is different from session to session.

This path seemed like a good balance between keeping the UI simple and not getting into the challenges of customizing for every different use case, while still allowing some ability to capture provider information for these important edge cases.  We also trade off the ability to perform more precise queries for which staff are providing services, but this capability isn't being used now and isn't an immediate priority.

Separately, but relatedly we also briefly considered updating this UI to support capturing finer-grained interventions like the difference between 1:1 Wilson, regular small group reading intervention, and occasional after school groups.  We didn't move forward with this since it increases challenges with data consistency and training across users and we wanted to focus on successful adoption at the current level of granularity first.

**Comment by alexsoble** [comment]
I think using free-text for service provider names will present challenges down the road. 

The data that educators input during SST meetings ultimately gets used in two ways:

1. It becomes part of a qualitative, narrative story in the Student Profile
2. It becomes part of a quantitative view of the whole school in the School Overview

If we make this a free-text field, it will be difficult to surface in the information in form (2). 

If we use a drop-down instead it will be easy to surface in form (2).

**Comment by kevinrobinson** [comment]
Ah okay yeah I completely agree so I think flubbed capturing this in writing. :)

What I took away was that there'd be a dropdown, but that we allow any arbitrary text to be entered as well.  I think I went right to "free-text," thinking about adding a new database column, and migrating the educator_ids to their text values.  We could also add a `provided_by_text` field and keep the `provided_by_educator_id`, and enforce that only one is set and let clients branch on that when querying or displaying.

Does that match what you're saying, or am I still flubbing it? :smile:

**Comment by alexsoble** [comment]
Let's say we have `provided_by_text`. Won't we run into problems like

```
LIST OF SERVICE PROVIDERS AT HEALEY SCHOOL

+ Kevin Robinson
+ Robinson, Kevin
+ Kevin Robinsoon
+ Kevin R
```

**Comment by kevinrobinson** [comment]
@alexsoble cool, thanks for chatting this out in Slack, and let's chat more in person next week, since I think I might have misunderstood this and we've got other important things to finish first :)

**Comment by alexsoble** [comment]
@kevinrobinson  👍

**Comment by alexsoble** [comment]
Started down the denormalizing path on the backend. 

Will finish this up later tonight or tomorrow. 

Was thinking about the front-end. I think to save time, perhaps we should have two separate input fields.

___Is this service being provided by a #{school.name} staff member?___ 

{{ educator dropdown }}

___Is this service being provided by someone outside #{school.name}?___

{{ free text input }}

No messing around with combo boxes...

**Comment by alexsoble** [comment]
@kevinrobinson and I talked about this feature over Slack and IRL. 

Here's an overview of what we discussed:

+ Currently, the drop-down list of staff providers is a blocker for capturing accurate data during SST meetings. When the SST notetaker can't find the right staff member, s/he assigns herself, which makes the data inaccurate.

+ One approach would be to try to add a bunch of options for all of the service providers who aren't directly employed by Somerville Public Schools. But this creates a new data field of outside service providers and a big new chunk of work. It might help us avoid the human-entered data problem outlined above, but we wouldn't be able to ship the feature quickly and it would add non-trivial complexity to the service-recording process.

+ So the plan is to capture a `provided_by_educator_name` for each service, denormalizing services from the `educators` table. This will let SST / MTSS note-takers enter any name, supported by a dropdown of previously-entered educator names, so they can quickly capture provider data. 

+ It's possible that the `provided_by_educator_name` will suffer from some human-entered data errors, but this is not a pressing issue right now because we are not querying for service providers anywhere in the app. If we decide in the future that querying by service provider is an important feature, we can double-check the data, do some cleanup, and run migrations to fix any issues.

**Comment by alexsoble** [comment]
As part of this change, I think we should make `provided_by_educator_name` optional. If a note-taker can't remember the provider name, or the service is provided by a group of people instead of one person, or some other complicating factor we can't think of arises — we don't want to run into the same issue we faced earlier of forcing note-takers to enter incorrect data in order to satisfy strict validation.

**Comment by alexsoble** [comment]
One side effect of denormalization within the profile page:

The `renderStaff` function outputs a list of staff who are supporting the student, with mailto links for contacting each staff person.

We'll need to either renormalize the `provided_by_educator_name` into a `provided_by_educator_id` when possible for a student who is receiving services, or drop features that require normalization / other data from X2 such as email address.

**Comment by alexsoble** [comment]
After doing some exploratory poking around, I'm going to break this into a series of smaller chunks of work as opposed to one big PR that changes the data structure and the UI at the same time.

At least three separate, non-interdependent, merge-able pieces of work that will reduce complexity in the Services sections of the Student Profile and make denormalizing simpler: 

1. Make provided_by_educator optional for Services
2. Remove deprecated Intervention model
3. Clarify "Support staff" summary list in student profile

**Comment by kevinrobinson** [comment]
@alexsoble This is amazing, just caught up on your incredible notes and explanation here.  I added it to the contributing doc as an example of what awesome communication on a pull request looks like! 😄

**Comment by alexsoble** [comment]
@kevinrobinson Aw, thanks Kevin!
