### ISSUE TITLE
Refactor StudentsController#show

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#365]
We are building up a very complex `@serialized_data` variable in StudentsController#show. The data from that variable gets passed through many components as it builds the StudentProfile page.

Forgetting to pass through the right prop name or calling the wrong part of `@serialized_data` leads to bugs, like this mistake I made: 
#363, fixed via #364

Goal would be to refactor `@serialized_data` toward two outcomes:
1. Fewer keys / values, simpler API for the React components to consume
2. Performance — we are probably duplicating queries

Not urgent (adding a "future" tag) but figured I'd document this soon after fixing a bug here.

**Comment by kevinrobinson** [comment]
@alexsoble Yeah, I think it'd be a great improvement to simplify threading these variables through the UI code as much as they are now.  Another approach is to use more `propTypes` to define the shape of the data the UI expects (eg., [here](https://github.com/studentinsights/studentinsights/blob/master/app/assets/javascripts/helpers/prop_types.js#L30)), like you add in this PR so that these kinds of bugs can result in Jasmine test failures.

**Comment by Jngai** [comment]
Hey @alexsoble I will be working on this.

**Comment by alexsoble** [comment]
Talked about this with @Jngai in our video call — this area of the code isn't really breaking or surfacing bugs, so let's close this and focus our energy on areas where we've seen bugs or issues, like the data import process and the Services area.
