### ISSUE TITLE
Fix bug with dates for Services on Student Profile

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#436]
Feedback from Kathleen Seward, principal at the West Somerville Neighborhood School:

Kathleen noticed that when she:

+ created a new Service in the Interventions tab,
+ and then went to the Profile Details / "Full Case History" tab,
+ the service would show a different date on each tab

My guess is that one is showing the service `date_started`, and the other is showing `recorded_at`. Looks like a bug to Kathleen. She expects both to show `date_started`.

**Comment by alexsoble** [comment]
@kevinrobinson How do you feel about adding this to the Profile V2 milestone?

**Comment by erose** [comment]
Actually, the problem is worse: Full Case History displays a single Service at the current date, and no others. Regardless of the actual data.

![screen shot 2016-04-29 at 1 56 09 pm](https://cloud.githubusercontent.com/assets/1514487/14924792/2bc35aae-0e12-11e6-9d6e-c3f23d474c1f.png)

I don't know if that changed recently and caused this, or if it was just always broken, but anyway the real problem is lack of spec. I'll make a spec.

**Comment by alexsoble** [comment]
@erose Love the diagnosis — lack of spec — and the solution — make a spec.  👍  😍

**Comment by kevinrobinson** [comment]
@alexsoble sorry I'm late here and thanks @erose for tackling this!
