### ISSUE TITLE
Update list of services in profile page

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#452]
We're not yet clear on the path forward here, current plan is:

> Remove reading intervention and math intervention, no academic interventions this round.

And discussing over email.  Tracking here as a loose end for this milestone.

**Comment by kevinrobinson** [comment]
Paraphrased from email with Uri:

Reading is being used in MTSS meetings, let's keep Reading Teacher with the definition from the user manual: `Reading Teacher: Student works with a reading specialist at least 4x/week for 30-40 minutes.`

**Comment by kevinrobinson** [comment]
Other context:

Uri currently tracks reading interventions in a spreadsheet, and then twice a year these are bulk uploaded into Aspent in a manual handoff to John.

**Comment by alexsoble** [comment]
Stole this assignment from you @kevinrobinson!  😊

**Comment by kevinrobinson** [comment]
@alexsoble 👍

**Comment by alexsoble** [comment]
We decided in last week's group meeting to go forward with Uri's latest proposal: keep the Reading Intervention option, get rid of Math Intervention, leaving us with a list of 6 services in profile page.

```
Counseling, in-house
Counseling, outside
Reading intervention
Attendance Officer
Attendance Contract
Behavior Contract
```

**Comment by alexsoble** [comment]
Did a preliminary database check to see if we have any Math interventions recorded so far.

Indeed we do: two recorded by the principal at West Somerville, and one recorded by a teacher at the Healey School.

**Comment by alexsoble** [comment]
Since users have already added a couple of Math intervention data points, I'd prefer not to delete data, delete the Math Intervention `ServiceType`, or remove any existing Math interventions from profile pages.

I'm thinking that a better route is simply to remove Math intervention from the array of Service Types passed to the student profile page front-end. So existing interventions stay, but users can't add new ones.

We should also write quick notes to the users who added Math interventions to explain why this button is going away. The reason is to provide fewer options with clearer definitions, so that we can have very high confidence in the data being entered.

**Comment by alexsoble** [comment]
This is complete!
