### ISSUE TITLE
No way to unselect Notes or Service type.

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#485]
Notes and Service types start with no options greyed out. When you click on one, it gets selected and the others grey out.

<img width="477" alt="screen shot 2016-05-14 at 5 40 50 pm" src="https://cloud.githubusercontent.com/assets/1514487/15270817/0750c23e-19fb-11e6-9cd5-aada82a666d1.png">

<img width="566" alt="screen shot 2016-05-14 at 5 42 21 pm" src="https://cloud.githubusercontent.com/assets/1514487/15270827/3f0580d4-19fb-11e6-8e02-8ee193d680d6.png">

From this state, there's no way to get back to the original state. You can still click on the greyed-out buttons to select them, so this doesn't prevent anyone from doing anything. My instinct is that it might be counterintuitive.

I would recommend letting the user de-select a button by clicking on it if it's already selected.

**Comment by jochakovsky** [comment]
@erose The way I see it, these buttons are basically a set of fancy-looking radio buttons. Normal radio buttons don't allow the possibility to easily return to the all-buttons-unselected state. I think that is totally OK for us too, since it is required to select one before saving, so I disagree that we should allow the user to un-select.

I do see how graying out the other options is confusing. As an alternative, maybe we should just put the outline around the selected button without graying out the rest?

For reference, here's how they look unselected:

<img width="346" alt="screenshot 2016-05-17 20 08 51" src="https://cloud.githubusercontent.com/assets/12554493/15343539/9348d03e-1c6b-11e6-9155-23d9d2635411.png">
