### ISSUE TITLE
Host our Docker image on Docker Hub?

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#487]
(Just sharing my thoughts while I brainstorm here).

[https://hub.docker.com/](Docker Hub) is like GitHub for Docker images. You can push and pull images. We use Docker Hub right now when we have `FROM ruby:2.3.0` at the top of our Dockerfile -- this means "pull the Ruby image, then start doing stuff to it".

Instead of just storing our `Dockerfile` on GitHub, we could store our image on Docker Hub. Then anyone who wants a copy of the app can just run `docker-compose up` to grab our image from Docker Hub. This is already how `docker-compose.yml` builds the `postgres` image.

What problems would this solve? Not sure exactly, still thinking about it.
* It would remove several tasks that new volunteers have to do. Right now they build from the `Dockerfile`, create the tables, then create the demo data.
* It would standardize demo data. Instead of having users create the demo data randomly themselves when setting up their environments, demo data would come with the app.

Okay, end brainstorm. That was fun, but doesn't seem worthwhile to do this right now.

**Comment by erose** [comment]
You can't ship two linked containers around on Docker Hub AFAIK, so I don't think this would actually solve the problems it says it does.

Better would be to include `rake db: <whatever>` in the docker-compose.yml.

**Comment by kevinrobinson** [comment]
@erose These are great things to be thinking of!

I set this up back in the day, exploring the same kinds of questions you're asking here.  The way I've been thinking about it is that Docker helps people not have to set up project dependencies (eg., Ruby versions, Postgres).  It might be nice to include the seeding as well, but that would also mean the primary workflow would be pulling down images (rather than working in Rails).  That might be interesting, but also means people writing migrations and thinking in Rails have to switch to think about containers and images rather than just pulling the latest source and interacting with Rails.

As for including `rake db:seed` etc. in the `docker-compose.yml`, if I'm following what you're thinking through, would that mean `docker-compuse up` re-seeds the database each time?  My own mental model is `docker-compose up` gives me access to the project running in containers, but doesn't actually do anything or take other actions.  But who knows!  figuring out how to make all these pieces simpler is great :)

**Comment by brisandbeans** [comment]
Here's a quick [bash script](https://gist.github.com/brisandbeans/331e90c1acc0b7313746a52db928b252)  illustrating one approach.
Note that the script expects to run every time the container starts. You could perform certain one-time initialization steps on a container _itself_. But what I believe you want is, in effect, for the `rails` container to initialize the `postgres` container's data volume, whose initialization status can be guessed but not easily known. So every time it runs, the start script tries a few things speculatively, with the expectation that some will fail most of the time. The cost is an extra ~10 seconds' delay before WEBrick starts, but maybe that could be reduced by someone who has more clues than I do.

All that said, I actually like the transparency of having to run the rake db commands myself, for a few reasons.

And incidentally, there's an experimental feature in the Docker release candidate for something called [Distributed Application Bundles](https://blog.docker.com/2016/06/docker-app-bundle/), which allow you to distribute linked services. You instantiate the bundle as a "stack". (It makes me think that Docker proper will soon absorb Docker Compose features.) Docker Hub support is probably in the works, but it's not there yet, last I checked.
