### ISSUE TITLE
Why did this Travis build fail?

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#490]
https://travis-ci.org/studentinsights/studentinsights/builds/130475484 fails the `rspec` tests.

The identical build from the same PR https://travis-ci.org/studentinsights/studentinsights/builds/130476319 succeeded, which makes me think that either this PR introduced some random element to our `rspec` suite (seems unlikely -- it didn't touch any Ruby code) or a random element was always there.

**Comment by erose** [comment]
Are we just missing a `.sort` in the line `expect(educator.allowed_homerooms).to eq`?

**Comment by alexsoble** [comment]
@erose Yep, that looks correct. The context block above uses `.sort` to eliminate the randomness.

**Comment by alexsoble** [comment]
Not sure why this would happen... Homeroom 101 should always be inserted into the database before Homeroom 102, since it's created on a preceding line. Can't imagine race conditions at work here.

If anyone else has ideas or hypotheses, let me know!

In any case, the order of homerooms in the array is irrelevant for authorization.

**Comment by erose** [comment]
I added it in a few more places.

**Comment by alexsoble** [comment]
@erose Ah OK. I'll close my PR since yours is more comprehensive.

**Comment by alexsoble** [comment]
@erose Oh shoot! Didn't realize you committed directly on top of my PR. Reopening.

**Comment by alexsoble** [comment]
@erose Taking a closer look, we don't want to call `.sort` on those last two examples.

For "teacher with grade level access", we don't want to call `.sort` because there's only one object in the array. No point in sorting it.

For "#allowed_homerooms_by_name", we're expecting the output array to come out in a certain order. Order matters here. So calling `.sort` on both sides of the equality negates the value of the spec.

**Comment by alexsoble** [comment]
Closed via #491.
