### ISSUE TITLE
Demo site throws 500 when trying to access homeroom

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#495]
e.g. https://somerville-teacher-tool-demo.herokuapp.com/homerooms/2

Doesn't happen on my dev server, which is up-to-date.

**Comment by alexsoble** [comment]
Oooooops, migrations were pending. 

Ran `rake db:migrate` against the demo site. Should be working now @erose.

**Comment by alexsoble** [comment]
Couple of thoughts:

1. @erose we should give you access to the demo site on Heroku. No student data there. Maybe this goes along with admin status on the repo.

2. Would be good to set up a hook to run `rake db:migrate` automatically against the demo site when new commits are pushed, otherwise its easy for the db schema to slip out of date.

**Comment by erose** [comment]
Closing this and making a new issue for your 2.
