### ISSUE TITLE
Add JS static analysis tools to test and build steps

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#550]
From @kbweaver, it'd be great to add some JS static analysis tools, things like [codeclimate](https://codeclimate.com/github/studentinsights/studentinsights) so that they run and comment on pull requests, or fail the build for particular rules (eg., 400 line functions).

This would be an awesome improvement!

**Comment by alexsoble** [comment]
We already have codeclimate: https://codeclimate.com/github/studentinsights/studentinsights. 

We don't have it integrated into the CI so that it runs against pull requests though, that would be a great step!

**Comment by alexsoble** [comment]
Still agree this is a good idea. Did a little more looking into CodeClimate. Turns out this is a paid feature: 

+ https://codeclimate.com/pricing

+ http://blog.codeclimate.com/blog/2013/11/06/code-climate-for-pull-requests/

I think it's something we should add one the next Somerville contract is signed.

**Comment by alexsoble** [comment]
We have this! 

`npm run lint`

And it's part of our CI

👍  ⭐️
