### ISSUE TITLE
Consolidate testing data for student event notes?

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#589]
When making a change to the structure of `event_note` in the feed, I had to change two files:
- `spec/javascripts/fixtures/fixture_students.js`
- `spec/javascripts/student_profile/fixtures.js`

What's the difference between these and when are they used? Can we make do with one?

**Comment by kevinrobinson** [comment]
@erose Good point!  The `student_profile/fixtures.js` was aimed at what's needed to test the profile page, while `fixture_students.js` was used to test the overview page.

One general thought is that it'd be great if it were simple to regenerate this fixture data when we make changes to our code.  If that's the case, then whether it's normalized or denormalized isn't super important.  It's difficult to generate these fixtures now, since the development demo data is generated randomly and so all the test values would need to be updated.  One direction we might take is to make the process of creating demo data deterministic by default (eg., set a consistent seed to the random number generator).  That seems like it might be a small change that simplify consistency across development environments and allow scripting generating these JS test fixtures.
