### ISSUE TITLE
Slow Healey overview page load

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#627]
Bug report from @erose!

**Comment by kevinrobinson** [comment]
I can't reproduce this now for any school page (using the sweet new district admin links).  It doesn't appear we retain metrics or logs long enough back to find out more information here.  This could definitely happen when requesting before the precompute job finishes, but since that happens in the wee hours of the morning it's unlikely to affect school users.

Logentries has some data showing a lot of variability in response times, with some responses taking >30seconds and timing out, and others completing in hundreds of ms.  It's just a guess, but it seems like something else is going on here.  I think in order to investigate further it'd help to set up more consistent traffic, maybe something like background jobs that query various pages every minute, so we can get a more consistent read on what response times are.  I took a stab at this here: https://github.com/studentinsights/studentinsights/pull/638

@alexsoble @erose Que piensas amigos?

**Comment by alexsoble** [comment]
@erose @kevinrobinson Kevin, it's possible you can't reproduce this anymore because I added the eager loads to the district admin links after Eli's QA: aa51005cb3816bb08667d79d99a52471446395ce

**Comment by kevinrobinson** [comment]
Here's an update.

I ran the pinger script in a few different combinations this morning, and moved it to https://github.com/studentinsights/studentinsights-pinger and deployed it https://dashboard.heroku.com/apps/studentinsights-pinger (private).  There's notes in chat.

I also investigated the memory errors we've been seeing.  These seem particularly relevant for understanding and improving response latency since these error message mean the Heroku runtime is spilling from RAM to disk (to avoid running out of memory and crashing the process).  More info here: https://devcenter.heroku.com/articles/ruby-memory-use

First I tried out https://github.com/schneems/derailed_benchmarks on the recommendation of the Heroku docs.  I just ran the static analysis which analyzes how much memory it takes to just require the project's gem dependencies.  There was nothing unexpected there (eg., Rails takes the most memory, it takes about 43MB to require all the gems).  Output is [here](https://gist.github.com/kevinrobinson/3b43139a14bb30be33a8e87d3f56172b) and [here](https://gist.github.com/kevinrobinson/20e5997d9299e36dd1eee0a55bd66de0).  There are other tools in derailed, but they require running the app in production mode so I didn't try them yet.

Next, I noticed we're running Unicorn and Heroku recommends Puma instead.  I didn't look at that but it would probably be worth doing separately.  As a first step, I tried reducing the number of Unicorn workers from 3 to 2 to see if that would improve memory usage and still be able to serve a handful of concurrent requests.  As a super rough test, I ran two pingers at the same time while repeatedly querying different pages manually.  This worked to reduce memory usage and fix the R14 errors and was still able to serve all requests within the same ballpark of latency.

Here's memory usage before and after:
<img width="164" alt="screen shot 2016-08-25 at 10 06 38 am" src="https://cloud.githubusercontent.com/assets/1056957/17972703/9e1d1f16-6aad-11e6-9dff-71cc1f0b9136.png">

This isn't a proper load test at all, even for low volume traffic, and that might be worth doing separately.  In monitoring this, I also set up https://devcenter.heroku.com/articles/log-runtime-metrics to get finer-resolution memory usage data.  It writes to the logs every 20 seconds, like this:
<img width="1007" alt="screen shot 2016-08-25 at 8 45 56 am" src="https://cloud.githubusercontent.com/assets/1056957/17972737/be278210-6aad-11e6-9228-e7cf51422b64.png">

I'll let the pinger run every 10minutes today, then check in on what response latencies look like at the end of today.

**Comment by alexsoble** [comment]
We found out that this was due to a large unnecessary query that was being triggered by an unsuspicious-looking `eager_load`.
