### ISSUE TITLE
Absences, tardies + discipline incidents not displayed on school overview page.

### ISSUE THREAD

**Issue by erose** [studentinsights/studentinsights#680]
This data is displayed on the student profile page, but right now, no school overview page in production has any of these events.

I think this is a data issue because it's only in production.

Is this the same issue as #673? I'm confused.

**Comment by kevinrobinson** [comment]
@erose Yes, I think this is a duplicate of #673.  My initial understanding is that no students should have any absences, tardies or discipline incidents yet since school doesn't start until Thursday :)  So I believe the profile pages are calculating the year cutoff incorrectly, leading to the inconsistency between the two views.

It could be a data issue, and you could verify that by picking one student that has a disrepancy and then seeing what's in the database via a Rails console.  This issue won't show up the same way in development though since the data is artificially generated, but a useful comparison for debugging might be the profile page for https://somerville-teacher-tool-demo.herokuapp.com/students/42 and then how that student looks on the overview: https://somerville-teacher-tool-demo.herokuapp.com/schools/brn#range%3Adiscipline_incidents_count%3A3%3A6, which I suspect is the same bug.

**Comment by erose** [comment]
Oh, of course. Brain fart --> I forgot that overview page displays for the current school year only.
