### ISSUE TITLE
Service Gets Recorded Even if No Teacher is Selected

### ISSUE THREAD

**Issue by Jngai** [studentinsights/studentinsights#976]
Under services, you don't have to specify the teacher for the form to post. I am wondering if this is a bug or was this intended by design?

At the moment, the form only checks if date and service type id exist before allowing access to record service.

![hello 1](https://user-images.githubusercontent.com/1547934/29580468-1cb20072-8744-11e7-8ec6-3399854da2cc.gif)

**Comment by kevinrobinson** [comment]
@Jngai Thanks!

I think the current behavior was intentional, but seems like it'd be a good idea to make it stricter.  Checking the production database, there are some records that do in fact have no educator entered, but it's only ~1% of all services recorded.

The changes in https://github.com/studentinsights/studentinsights/pull/1041/files#diff-6e6d6d92b78948abf256f6dfaaa28bb4R95 change this to be stricter (but still allow empty string in the database for the older records), and adds a test for this as well.
