### ISSUE TITLE
Refactor: move from mixins (modules) to object-oriented classes for querying data

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#989]
# What

+ Move from modules for classes to encapsulate the queries needed for each page.
+ Create one class per page:

```
class SchoolOverviewQuery
end
```

```
class StudentProfileQuery
end
```

```
class HomeroomRosterQuery
end
```

etc.

# Why

+ Each page has slightly different data needs. 
+ Right now they pull in data using `include`:

```
include SerializeDataHelper
include StudentsQueryHelper
```

+ `include` encourages us to use the same queries across pages. Downside: this can cause us to pull in more data (and allocate way more memory) than we might need on a particular page. 
  + Example: Looks like we're pulling in way more EventNoteRevision records that we need to for the School Overview page, which could be dragging down the page and contributing to memory problems: https://github.com/studentinsights/studentinsights/issues/988#issuecomment-325204636
  + Also makes it hard for the developer to trace the flow of methods that build up data for the page.

# How 

+ Build up the classes sketched out above 
+ Keep all the module-based code in place until it's not called by any of the pages and can be safely deleted

**Comment by jhilde** [comment]
Are you thinking of pulling the queries out of active record generated ones to optimize them?

Should also add SectionRoster into the mix as well.

**Comment by alexsoble** [comment]
@jhilde Yep, SectionRoster should follow the same pattern!

Not thinking about pulling the queries out of ActiveRecord.

**Comment by jhilde** [comment]
So you’re thinking about centralizing them? Trying to understand the rationale?

On Mon, Aug 28, 2017 at 1:57 PM Alex Soble

<
mailto:Alex Soble <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/jhilde
Yep, SectionRoster should follow the same pattern!

Not thinking about pulling the queries out of ActiveRecord.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/studentinsights/studentinsights/issues/989#issuecomment-325427819
, or

**Comment by alexsoble** [comment]
@jhilde Added a little more information about context / rationale above. The goal is to keep query-related code for the School Overview page encapsulated and separate from query-related code for the Student Profile page to make it harder to pull in more data than we need for each view.

**Comment by kevinrobinson** [comment]
we did this!
